-- V085 ROLLBACK : Restaurer EXECUTION_STEPS non-partitionnée
-- Story 40.3 - Epic 40: Partitionnement et rétention tables performance
--
-- USAGE DBA MANUEL UNIQUEMENT — Ce script n'est PAS exécuté par Flyway.
-- À utiliser en cas de problème après exécution de V085__partition_execution_steps.sql.
--
-- PRÉREQUIS :
--   1. Identifier le scénario applicable (voir ci-dessous)
--   2. Effectuer un backup avant exécution
--   3. Planifier une fenêtre de maintenance (durée estimée: 2-4h selon volume)
--   4. Valider sur DEV/PREPROD avant application PROD
--
-- DIAGNOSTIC PRÉLIMINAIRE :
--   SELECT TABLE_NAME FROM USER_TABLES
--   WHERE TABLE_NAME IN ('EXECUTION_STEPS','EXECUTION_STEPS_NEW','EXECUTION_STEPS_OLD');
--
-- SCÉNARIOS DE ROLLBACK :
--   Scénario A : V085 a échoué avant la Phase 4 (EXECUTION_STEPS_OLD n'existe pas)
--     → EXECUTION_STEPS originale encore intacte, EXECUTION_STEPS_NEW à supprimer
--     → Exécuter : Section A ci-dessous
--
--   Scénario B : V085 a échoué pendant/après Phase 4 (EXECUTION_STEPS_OLD existe)
--     → EXECUTION_STEPS_OLD existe, la table EXECUTION_STEPS est la version partitionnée
--     → Exécuter : Section B ci-dessous (rollback complet)
--
--   Scénario C : V085 s'est terminée avec succès (EXECUTION_STEPS_OLD a été supprimée)
--     → Rollback doit recréer la table non-partitionnée depuis EXECUTION_STEPS partitionnée
--     → Exécuter : Section C ci-dessous (rollback post-succès)
--

-- ===========================================================================
-- SECTION A : Nettoyage si échec avant Phase 4 (EXECUTION_STEPS intacte)
-- ===========================================================================
-- Applicable si EXECUTION_STEPS existe ET EXECUTION_STEPS_OLD n'existe pas.
-- EXECUTION_STEPS originale est intacte.

/*
-- Supprimer EXECUTION_STEPS_NEW (création partielle ou données incomplètes)
DROP TABLE EXECUTION_STEPS_NEW PURGE;

-- Supprimer la table de contrôle si elle existe
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EXEC_STEPS_MIGRATION_CHECK PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;  -- ORA-00942: table ou vue inexistante
END;
/

-- EXECUTION_STEPS originale est intacte, aucune autre action requise.
-- Flyway doit être réinitialisé pour permettre une ré-exécution de V085 corrigée :
--   DELETE FROM flyway_schema_history WHERE version = '085';
--   COMMIT;
*/

-- ===========================================================================
-- SECTION B : Rollback complet depuis EXECUTION_STEPS_OLD (échec mid-migration)
-- ===========================================================================
-- Applicable si EXECUTION_STEPS_OLD existe (Phase 4 a été exécutée mais V085 a échoué ensuite).
-- EXECUTION_STEPS est la version partitionnée (potentiellement incomplète).

/*
-- Étape B.1 : Supprimer la version partitionnée (EXECUTION_STEPS = anciennement EXECUTION_STEPS_NEW)
-- Note: Aucune FK entrante vers EXECUTION_STEPS — pas de DISABLE/ENABLE nécessaire
DROP TABLE EXECUTION_STEPS PURGE;

-- Étape B.2 : Renommer EXECUTION_STEPS_OLD → EXECUTION_STEPS
ALTER TABLE EXECUTION_STEPS_OLD RENAME TO EXECUTION_STEPS;

-- Étape B.3 : Supprimer la table de contrôle si elle existe
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EXEC_STEPS_MIGRATION_CHECK PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Étape B.4 : Valider
SELECT COUNT(*) AS EXECUTION_STEPS_COUNT FROM EXECUTION_STEPS;
SELECT PARTITIONED FROM USER_TABLES WHERE TABLE_NAME = 'EXECUTION_STEPS';
-- PARTITIONED doit être 'NO'
*/

-- ===========================================================================
-- SECTION C : Rollback post-succès (EXECUTION_STEPS_OLD supprimée)
-- ===========================================================================
-- Applicable si V085 s'est terminée avec succès et que EXECUTION_STEPS_OLD n'existe plus.
-- Cette section recrée une table non-partitionnée depuis la table partitionnée actuelle.
-- ATTENTION : Opération longue selon volume (estimation : 2-4h pour volumes PROD).

/*
-- Étape C.0 : Vérification
DECLARE
    v_partitioned VARCHAR2(3);
BEGIN
    SELECT PARTITIONED INTO v_partitioned FROM USER_TABLES WHERE TABLE_NAME = 'EXECUTION_STEPS';
    IF v_partitioned != 'YES' THEN
        RAISE_APPLICATION_ERROR(-20010, 'EXECUTION_STEPS n''est pas partitionnée - rollback inutile');
    END IF;
    DBMS_OUTPUT.PUT_LINE('EXECUTION_STEPS est bien partitionnée (Reference) - rollback applicable');
END;
/

-- Étape C.1 : Capturer COUNT de référence
CREATE TABLE EXEC_STEPS_ROLLBACK_CHECK AS
    SELECT COUNT(*) AS ROW_COUNT FROM EXECUTION_STEPS;

-- Étape C.2 : Créer la table non-partitionnée de destination
-- Colonnes conformes à l'état post-V048 (TIMESTAMP plain, plus WITH TIME ZONE)
CREATE TABLE EXECUTION_STEPS_NOPART (
    ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    EXECUTION_ID    NUMBER NOT NULL,
    STEP_ORDER      NUMBER NOT NULL,
    STEP_NAME       VARCHAR2(255) NOT NULL,
    STEP_TYPE       VARCHAR2(50) NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    STARTED_AT      TIMESTAMP,
    COMPLETED_AT    TIMESTAMP,
    OUTPUT          CLOB,
    PLATFORM_JOB_ID VARCHAR2(255),
    ERROR_MESSAGE   CLOB,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_EXEC_STEPS_NOPART PRIMARY KEY (ID),
    CONSTRAINT FK_EXEC_STEPS_NOPART_EXEC
        FOREIGN KEY (EXECUTION_ID) REFERENCES EXECUTIONS(ID) ON DELETE CASCADE
);

-- Étape C.3 : Copier les données
INSERT /*+ APPEND PARALLEL(4) */ INTO EXECUTION_STEPS_NOPART
    (ID, EXECUTION_ID, STEP_ORDER, STEP_NAME, STEP_TYPE, STATUS,
     STARTED_AT, COMPLETED_AT, OUTPUT, PLATFORM_JOB_ID, ERROR_MESSAGE, CREATED_AT)
SELECT
     ID, EXECUTION_ID, STEP_ORDER, STEP_NAME, STEP_TYPE, STATUS,
     STARTED_AT, COMPLETED_AT, OUTPUT, PLATFORM_JOB_ID, ERROR_MESSAGE, CREATED_AT
FROM EXECUTION_STEPS;
COMMIT;

-- Recaler la séquence IDENTITY
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(ID), 0) INTO v_max FROM EXECUTION_STEPS_NOPART;
    IF v_max > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE EXECUTION_STEPS_NOPART MODIFY ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH '
            || (v_max + 1) || ' INCREMENT BY 1 NOCACHE)';
    END IF;
END;
/

-- Étape C.4 : Valider COUNT avant renommage
DECLARE
    v_orig NUMBER;
    v_new  NUMBER;
BEGIN
    SELECT ROW_COUNT INTO v_orig FROM EXEC_STEPS_ROLLBACK_CHECK;
    SELECT COUNT(*) INTO v_new FROM EXECUTION_STEPS_NOPART;
    IF v_new != v_orig THEN
        RAISE_APPLICATION_ERROR(-20011,
            'ROLLBACK COUNT MISMATCH: original=' || v_orig || ', restored=' || v_new);
    END IF;
    DBMS_OUTPUT.PUT_LINE('Rollback count validated: ' || v_new || ' rows');
END;
/

-- Étape C.5 : Supprimer la version partitionnée
-- Note: Aucune FK entrante vers EXECUTION_STEPS — DROP direct sans DISABLE/ENABLE
DROP TABLE EXECUTION_STEPS PURGE;

-- Étape C.6 : Renommer la version non-partitionnée
ALTER TABLE EXECUTION_STEPS_NOPART RENAME TO EXECUTION_STEPS;
ALTER TABLE EXECUTION_STEPS RENAME CONSTRAINT PK_EXEC_STEPS_NOPART TO PK_EXECUTION_STEPS;
ALTER TABLE EXECUTION_STEPS RENAME CONSTRAINT FK_EXEC_STEPS_NOPART_EXEC TO FK_EXEC_STEPS_EXECUTION;

-- Étape C.7 : Recréer les CHECK constraints (état pré-V085 = post-V067)
ALTER TABLE EXECUTION_STEPS ADD CONSTRAINT CHK_STEP_STATUS
    CHECK (STATUS IN ('PENDING', 'WAITING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED'));
ALTER TABLE EXECUTION_STEPS ADD CONSTRAINT CHK_STEP_TYPE
    CHECK (STEP_TYPE IN ('vault', 'servicenow', 'platform', 'prerequisite', 'verification'));

-- Étape C.8 : Recréer la contrainte UNIQUE (état pré-V085)
ALTER TABLE EXECUTION_STEPS ADD CONSTRAINT UQ_EXEC_STEP_ORDER
    UNIQUE (EXECUTION_ID, STEP_ORDER);

-- Étape C.9 : Recréer les index (état pré-V085)
CREATE INDEX IDX_EXEC_STEPS_EXECUTION_ID ON EXECUTION_STEPS(EXECUTION_ID);
CREATE INDEX IDX_EXEC_STEPS_STATUS ON EXECUTION_STEPS(STATUS);

-- Étape C.10 : Nettoyage final
DROP TABLE EXEC_STEPS_ROLLBACK_CHECK PURGE;

-- Étape C.11 : Valider état final
SELECT PARTITIONED FROM USER_TABLES WHERE TABLE_NAME = 'EXECUTION_STEPS';
-- Doit être 'NO'
SELECT COUNT(*) AS FINAL_COUNT FROM EXECUTION_STEPS;
*/

-- ===========================================================================
-- FLYWAY : Marquer V085 comme annulée dans flyway_schema_history
-- ===========================================================================
-- Après exécution du rollback, supprimer l'entrée V085 de Flyway pour permettre
-- une ré-exécution ou un saut de version :
--
-- DELETE FROM flyway_schema_history WHERE version = '085';
-- COMMIT;
--
-- Puis si vous souhaitez sauter définitivement V085 (sans re-exécuter) :
-- INSERT INTO flyway_schema_history (installed_rank, version, description, type, script,
--     checksum, installed_by, installed_on, execution_time, success)
-- VALUES (
--     (SELECT NVL(MAX(installed_rank),0)+1 FROM flyway_schema_history),
--     '085',
--     'partition_execution_steps - ROLLED BACK',
--     'SQL',
--     'V085__partition_execution_steps.sql',
--     0,
--     USER,
--     SYSDATE,
--     0,
--     1
-- );
-- COMMIT;
