# Generated by Django 5.2.11 on 2026-02-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255, unique=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=4000, null=True)),
                ('ad_group', models.CharField(db_column='AD_GROUP', max_length=512)),
                ('is_admin', models.IntegerField(db_column='IS_ADMIN', default=0)),
                ('is_auditor', models.IntegerField(db_column='IS_AUDITOR', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'db_table': 'PROFILES',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileActionPermission',
            fields=[
                ('profile', models.OneToOneField(db_column='PROFILE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.profile')),
                ('permission_type', models.CharField(choices=[('LIST', 'List'), ('PATTERN', 'Pattern'), ('ALL', 'All')], db_column='PERMISSION_TYPE', max_length=20)),
                ('action_ids_json', models.TextField(blank=True, db_column='ACTION_IDS_JSON', null=True)),
                ('tag_patterns_json', models.TextField(blank=True, db_column='TAG_PATTERNS_JSON', null=True)),
                ('environments_json', models.TextField(blank=True, db_column='ENVIRONMENTS_JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'db_table': 'PROFILE_ACTION_PERMISSIONS',
            },
        ),
        migrations.CreateModel(
            name='ProfileTargetPermission',
            fields=[
                ('profile', models.OneToOneField(db_column='PROFILE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.profile')),
                ('permission_type', models.CharField(choices=[('LIST', 'List'), ('PATTERN', 'Pattern'), ('ALL', 'All')], db_column='PERMISSION_TYPE', max_length=20)),
                ('target_names_json', models.TextField(blank=True, db_column='TARGET_NAMES_JSON', null=True)),
                ('target_patterns_json', models.TextField(blank=True, db_column='TARGET_PATTERNS_JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'db_table': 'PROFILE_TARGET_PERMISSIONS',
            },
        ),
    ]
