# Generated by Django 5.2.11 on 2026-02-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idp_auth', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'TAGS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255, unique=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=4000, null=True)),
                ('category', models.CharField(choices=[('Provisioning', 'Provisioning'), ('Patching', 'Patching'), ('Administration', 'Administration'), ('Monitoring', 'Monitoring')], db_column='CATEGORY', max_length=50)),
                ('engine', models.CharField(choices=[('Oracle', 'Oracle'), ('SQL Server', 'SQL Server'), ('DB2', 'DB2')], db_column='ENGINE', max_length=50)),
                ('platform', models.CharField(choices=[('AAP', 'AAP'), ('GitHub Actions', 'GitHub Actions'), ('Azure DevOps', 'Azure DevOps'), ('Terraform', 'Terraform')], db_column='PLATFORM', max_length=50)),
                ('parameters_schema', models.TextField(blank=True, db_column='PARAMETERS_SCHEMA', null=True)),
                ('impact_rules', models.TextField(blank=True, db_column='IMPACT_RULES', null=True)),
                ('change_type_config', models.TextField(blank=True, db_column='CHANGE_TYPE_CONFIG', null=True)),
                ('documentation_md', models.TextField(blank=True, db_column='DOCUMENTATION_MD', null=True)),
                ('remediation_rules', models.TextField(blank=True, db_column='REMEDIATION_RULES', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('disabled', 'Disabled')], db_column='STATUS', default='draft', max_length=20)),
                ('item_type', models.CharField(choices=[('action', 'Action'), ('workflow', 'Workflow')], db_column='ITEM_TYPE', default='action', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UPDATED_AT', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, to='idp_auth.user')),
                ('integration', models.ForeignKey(blank=True, db_column='INTEGRATION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.integration')),
            ],
            options={
                'db_table': 'ACTIONS_CATALOG',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.CASCADE, to='catalog.action')),
                ('tag', models.ForeignKey(db_column='TAG_ID', on_delete=django.db.models.deletion.CASCADE, to='catalog.tag')),
            ],
            options={
                'db_table': 'ACTION_TAGS',
                'unique_together': {('action', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('action', models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.CASCADE, to='catalog.action')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to='idp_auth.user')),
            ],
            options={
                'db_table': 'USER_FAVORITES',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'action')},
            },
        ),
    ]
