# Generated by Django 5.2.11 on 2026-02-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="default_impact_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                db_column="DEFAULT_IMPACT_LEVEL",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="execution_steps",
            field=models.TextField(blank=True, db_column="EXECUTION_STEPS", null=True),
        ),
        migrations.AddField(
            model_name="action",
            name="requires_target",
            field=models.BooleanField(db_column="REQUIRES_TARGET", default=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="engine",
            field=models.CharField(
                db_column="ENGINE",
                help_text="Engine code (must exist in REF_ENGINES.CODE). Validated by application logic.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="platform",
            field=models.CharField(
                db_column="PLATFORM",
                help_text="Platform code (must exist in REF_PLATFORMS.CODE). Validated by application logic.",
                max_length=50,
            ),
        ),
    ]
