# Generated by Django 5.2.11 on 2026-02-07 17:49

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_action_default_impact_level_action_execution_steps_and_more"),
        ("idp_auth", "0001_initial"),
        ("integrations", "0002_integration_auth_flow_integration_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="change_type_config",
            field=core.fields.OracleJSONField(
                blank=True, db_column="CHANGE_TYPE_CONFIG", null=True
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="execution_steps",
            field=core.fields.OracleJSONField(
                blank=True, db_column="EXECUTION_STEPS", null=True
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="impact_rules",
            field=core.fields.OracleJSONField(
                blank=True, db_column="IMPACT_RULES", null=True
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="parameters_schema",
            field=core.fields.OracleJSONField(
                blank=True, db_column="PARAMETERS_SCHEMA", null=True
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="remediation_rules",
            field=core.fields.OracleJSONField(
                blank=True, db_column="REMEDIATION_RULES", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["status"], name="idx_actions_status"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["status", "engine"], name="idx_actions_status_engine"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["status", "created_at"], name="idx_actions_status_created"
            ),
        ),
    ]
