# Generated by Django 5.2.11 on 2026-02-07 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_action_change_type_config_and_more"),
        ("idp_auth", "0001_initial"),
        ("integrations", "0002_integration_auth_flow_integration_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_column="DELETED_AT", null=True),
        ),
        migrations.AddField(
            model_name="action",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_column="DELETED_BY",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_actions",
                to="idp_auth.user",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="deletion_reason",
            field=models.CharField(
                blank=True, db_column="DELETION_REASON", max_length=500, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["deleted_at"], name="idx_actions_deleted_at"),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("deleted_at__isnull", False), ("status", "disabled")),
                    models.Q(
                        ("deleted_at__isnull", True),
                        ("status__in", ["draft", "published"]),
                    ),
                    _connector="OR",
                ),
                name="ck_actions_soft_delete_consistency",
            ),
        ),
    ]
