# Generated by Django 5.2.11 on 2026-02-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_add_soft_delete_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="category",
            field=models.CharField(
                blank=True,
                db_column="CATEGORY",
                help_text="Category code (must exist in REF_CATEGORIES.CODE). Validated by application logic.",
                max_length=50,
                null=True,
            ),
        ),
    ]
