# Generated by Django 5.2.11 on 2026-02-15 20:13

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_add_business_rule_policies"),
        ("idp_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="business_rule_policies",
            field=core.fields.OracleJSONField(
                blank=True,
                db_column="BUSINESS_RULE_POLICIES",
                help_text="JSON schema defining business rule policies evaluated on step output (legacy inline)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BusinessRulePolicy",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(db_column="NAME", max_length=200, unique=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_column="DESCRIPTION", max_length=500, null=True
                    ),
                ),
                ("policy_json", core.fields.OracleJSONField(db_column="POLICY_JSON")),
                ("is_active", models.BooleanField(db_column="IS_ACTIVE", default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CREATED_AT"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UPDATED_AT"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CREATED_BY_ID",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="idp_auth.user",
                    ),
                ),
            ],
            options={
                "db_table": "BUSINESS_RULE_POLICIES",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="action",
            name="business_rule_policy",
            field=models.ForeignKey(
                blank=True,
                db_column="BUSINESS_RULE_POLICY_ID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="catalog.businessrulepolicy",
            ),
        ),
    ]
