# Generated by Django 5.2.11 on 2026-02-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(db_column="CODE", max_length=50, unique=True),
                ),
                ("label", models.CharField(db_column="LABEL", max_length=100)),
                (
                    "display_order",
                    models.IntegerField(db_column="DISPLAY_ORDER", default=0),
                ),
                ("is_active", models.IntegerField(db_column="IS_ACTIVE", default=1)),
            ],
            options={
                "verbose_name": "Category Reference",
                "verbose_name_plural": "Category References",
                "db_table": "REF_CATEGORIES",
                "ordering": ["display_order", "code"],
            },
        ),
    ]
