"""Tests for SQL migration V001 (AC #6). Story 2.20: Flyway naming, identity column."""

from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).parent.parent.parent.parent  # idp-portal/
MIGRATIONS_DIR = PROJECT_ROOT / "database" / "migrations"

V001_FILE = "V001__create_users.sql"


def test_v001_file_exists():
    """AC #6: V001 migration file exists (Flyway convention V001__desc.sql)."""
    assert (MIGRATIONS_DIR / V001_FILE).is_file()


def test_v001_creates_users_table():
    """AC #6: V001 contains CREATE TABLE USERS."""
    sql = (MIGRATIONS_DIR / V001_FILE).read_text()
    assert "CREATE TABLE USERS" in sql


def test_v001_uses_identity_column():
    """Story 2.20: V001 uses identity column for ID (no sequence)."""
    sql = (MIGRATIONS_DIR / V001_FILE).read_text()
    assert "GENERATED ALWAYS AS IDENTITY" in sql or "GENERATED BY DEFAULT AS IDENTITY" in sql


def test_v001_creates_unique_index():
    """AC #6: V001 contains unique index on USERNAME."""
    sql = (MIGRATIONS_DIR / V001_FILE).read_text()
    assert "UK_USERS_USERNAME" in sql


def test_v001_columns():
    """AC #6: V001 has all required columns."""
    sql = (MIGRATIONS_DIR / V001_FILE).read_text()
    for col in ["ID", "USERNAME", "DISPLAY_NAME", "PROFILE", "SAML_SUBJECT", "CREATED_AT", "UPDATED_AT"]:
        assert col in sql, f"Missing column {col}"


def test_run_migrations_script_exists():
    """AC #6: Migration script exists at expected path."""
    script = PROJECT_ROOT / "scripts" / "run_migrations.sh"
    assert script.is_file()


# Story 2.20 AC4: identity columns for all tables with auto-generated ID
_IDENTITY_MIGRATIONS = [
    ("V004__create_audit_log.sql", "AUDIT_LOG"),
    ("V006__create_execution_log.sql", "EXECUTION_LOG"),
    ("V007__create_tags_and_action_tags.sql", "TAGS"),
    ("V010__create_profiles.sql", "PROFILES"),
]


def _read_migration(name: str) -> str:
    return (MIGRATIONS_DIR / name).read_text()


@pytest.mark.parametrize("filename,table_hint", _IDENTITY_MIGRATIONS)
def test_migration_uses_identity_column(filename, table_hint):
    """Story 2.20: Migration uses identity column for ID (no sequence)."""
    sql = _read_migration(filename)
    assert "GENERATED ALWAYS AS IDENTITY" in sql or "GENERATED BY DEFAULT AS IDENTITY" in sql, (
        f"{filename} should define ID as GENERATED ... AS IDENTITY for {table_hint}"
    )


# Story 2.24: V019 change_type_config per environment
V019_FILE = "V019__change_type_config_per_env.sql"


def test_v019_file_exists():
    """Story 2.24: V019 migration file exists (change_type_config per env)."""
    assert (MIGRATIONS_DIR / V019_FILE).is_file()


def test_v019_drops_change_model_code_column():
    """Story 2.24 AC4: V019 drops CHANGE_MODEL_CODE column from ACTIONS_CATALOG."""
    sql = _read_migration(V019_FILE)
    assert "DROP COLUMN CHANGE_MODEL_CODE" in sql
    assert "ACTIONS_CATALOG" in sql


def test_v019_migrates_change_type_config_to_new_format():
    """Story 2.24: V019 updates CHANGE_TYPE_CONFIG from env->pre_approved to env->{required, change_model_code}."""
    sql = _read_migration(V019_FILE)
    assert "CHANGE_TYPE_CONFIG" in sql
    assert "required" in sql
    assert "change_model_code" in sql
    assert "JSON_OBJECT_T" in sql or "pre_approved" in sql


def test_v019_comment_documents_new_format():
    """Story 2.24: V019 documents new CHANGE_TYPE_CONFIG format in COMMENT."""
    sql = _read_migration(V019_FILE)
    assert "COMMENT ON COLUMN" in sql
    assert "required" in sql and "change_model_code" in sql


# Story 3.1: V021 USER_FAVORITES table (AC14)
V021_FILE = "V021__create_user_favorites.sql"


def test_v021_file_exists():
    """Story 3.1 AC14: V021 migration file exists (USER_FAVORITES table)."""
    assert (MIGRATIONS_DIR / V021_FILE).is_file()


def test_v021_creates_user_favorites_table():
    """Story 3.1 AC14: V021 creates USER_FAVORITES table."""
    sql = _read_migration(V021_FILE)
    assert "CREATE TABLE USER_FAVORITES" in sql


def test_v021_has_required_columns():
    """Story 3.1 AC14: USER_FAVORITES has user_id, action_id, created_at columns."""
    sql = _read_migration(V021_FILE)
    for col in ["USER_ID", "ACTION_ID", "CREATED_AT"]:
        assert col in sql, f"Missing column {col}"


def test_v021_has_primary_key():
    """Story 3.1 AC14: USER_FAVORITES has composite PK on (user_id, action_id)."""
    sql = _read_migration(V021_FILE)
    assert "PRIMARY KEY" in sql
    assert "USER_ID" in sql and "ACTION_ID" in sql


def test_v021_has_foreign_keys():
    """Story 3.1 AC14: USER_FAVORITES has FK to USERS and ACTIONS_CATALOG."""
    sql = _read_migration(V021_FILE)
    assert "REFERENCES USERS" in sql
    assert "REFERENCES ACTIONS_CATALOG" in sql


def test_v021_has_index_on_user_id():
    """Story 3.1 AC14: USER_FAVORITES has index on user_id for efficient lookups."""
    sql = _read_migration(V021_FILE)
    assert "INDEX" in sql and "USER_ID" in sql
