# Generated by Django 5.2.11 on 2026-02-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('idp_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('prod', 'Production')], db_column='ENVIRONMENT', max_length=50)),
                ('parameters', models.TextField(blank=True, db_column='PARAMETERS', null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], db_column='STATUS', default='SUBMITTED', max_length=20)),
                ('servicenow_change_id', models.CharField(blank=True, db_column='SERVICENOW_CHANGE_ID', max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='APPROVED_AT', null=True)),
                ('approval_comment', models.CharField(blank=True, db_column='APPROVAL_COMMENT', max_length=1000, null=True)),
                ('started_at', models.DateTimeField(blank=True, db_column='STARTED_AT', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_column='COMPLETED_AT', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('action', models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.CASCADE, to='catalog.action')),
                ('approved_by', models.ForeignKey(blank=True, db_column='APPROVED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_executions', to='idp_auth.user')),
                ('parent_execution', models.ForeignKey(blank=True, db_column='PARENT_EXECUTION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_executions', to='executions.execution')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to='idp_auth.user')),
            ],
            options={
                'db_table': 'EXECUTIONS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledExecution',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('prod', 'Production')], db_column='ENVIRONMENT', max_length=50)),
                ('parameters', models.TextField(blank=True, db_column='PARAMETERS', null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_column='SCHEDULED_AT', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], db_column='STATUS', default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UPDATED_AT', null=True)),
                ('action', models.ForeignKey(db_column='ACTION_ID', on_delete=django.db.models.deletion.CASCADE, to='catalog.action')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to='idp_auth.user')),
            ],
            options={
                'db_table': 'SCHEDULED_EXECUTIONS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('one_time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('cron', 'Cron')], db_column='PATTERN_TYPE', max_length=50)),
                ('pattern_config', models.TextField(blank=True, db_column='PATTERN_CONFIG', null=True)),
                ('next_execution_date', models.DateTimeField(db_column='NEXT_EXECUTION_DATE')),
                ('is_active', models.IntegerField(db_column='IS_ACTIVE', default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UPDATED_AT', null=True)),
                ('scheduled_execution', models.OneToOneField(db_column='SCHEDULED_EXECUTION_ID', on_delete=django.db.models.deletion.CASCADE, to='executions.scheduledexecution')),
            ],
            options={
                'db_table': 'RECURRING_PATTERNS',
            },
        ),
        migrations.CreateModel(
            name='ExecutionStep',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('step_order', models.IntegerField(db_column='STEP_ORDER')),
                ('step_name', models.CharField(db_column='STEP_NAME', max_length=255)),
                ('step_type', models.CharField(choices=[('vault', 'Vault'), ('servicenow', 'ServiceNow'), ('platform', 'Platform'), ('prerequisite', 'Prerequisite'), ('verification', 'Verification')], db_column='STEP_TYPE', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_column='STATUS', default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, db_column='STARTED_AT', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_column='COMPLETED_AT', null=True)),
                ('output', models.TextField(blank=True, db_column='OUTPUT', null=True)),
                ('platform_job_id', models.CharField(blank=True, db_column='PLATFORM_JOB_ID', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, db_column='ERROR_MESSAGE', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('execution', models.ForeignKey(db_column='EXECUTION_ID', on_delete=django.db.models.deletion.CASCADE, to='executions.execution')),
            ],
            options={
                'db_table': 'EXECUTION_STEPS',
                'ordering': ['execution', 'step_order'],
                'unique_together': {('execution', 'step_order')},
            },
        ),
    ]
