# Generated by Django 5.2.11 on 2026-02-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledexecution",
            name="correlation_id",
            field=models.CharField(
                blank=True, db_column="CORRELATION_ID", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="scheduledexecution",
            name="execution_id",
            field=models.BigIntegerField(
                blank=True, db_column="EXECUTION_ID", null=True
            ),
        ),
    ]
