# Generated by Django 5.2.11 on 2026-02-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    # Story 17.17 FIX#5 & FIX#6: Remove unnecessary dependency on catalog.0003
    # This migration only creates an index on EXECUTIONS table, does not depend on catalog changes

    dependencies = [
        ("executions", "0002_scheduledexecution_correlation_id_and_more"),
        ("idp_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(
                fields=["action", "created_at"], name="idx_exec_action_created"
            ),
        ),
    ]
