# Generated by Django 5.2.11 on 2026-02-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0003_execution_idx_exec_action_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="error_message",
            field=models.TextField(blank=True, db_column="ERROR_MESSAGE", null=True),
        ),
        migrations.AlterField(
            model_name="execution",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("INTEGRATION_ERROR", "Integration Error"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("REJECTED", "Rejected"),
                ],
                db_column="STATUS",
                default="SUBMITTED",
                max_length=20,
            ),
        ),
    ]
