# Generated by Django 5.2.11 on 2026-02-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0004_execution_error_message_alter_execution_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("SERVER", "Server"),
                            ("DATABASE", "Database"),
                            ("INSTANCE", "Instance"),
                            ("SCHEMA", "Schema"),
                            ("CLUSTER", "Cluster"),
                            ("OTHER", "Other"),
                        ],
                        db_column="TARGET_TYPE",
                        max_length=50,
                    ),
                ),
                ("target_id", models.CharField(db_column="TARGET_ID", max_length=200)),
                (
                    "target_name",
                    models.CharField(db_column="TARGET_NAME", max_length=255),
                ),
                (
                    "target_metadata",
                    models.TextField(
                        blank=True, db_column="TARGET_METADATA", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CREATED_AT"),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        db_column="EXECUTION_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="executions.execution",
                    ),
                ),
            ],
            options={
                "db_table": "EXECUTION_TARGETS",
                "unique_together": {("execution", "target_type", "target_id")},
            },
        ),
    ]
