# Generated by Django 5.2.11 on 2026-03-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0008_executionstep_approved_fields_and_new_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledexecution",
            name="source_execution_id",
            field=models.BigIntegerField(
                blank=True, db_column="SOURCE_EXECUTION_ID", null=True
            ),
        ),
    ]
