# Generated by Django 5.2.11 on 2026-03-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0009_add_source_execution_id_to_scheduledexecution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("vault", "Vault"),
                    ("servicenow", "ServiceNow"),
                    ("platform", "Platform"),
                    ("prerequisite", "Prerequisite"),
                    ("verification", "Verification"),
                    ("service_call", "Service Call"),
                    ("http_request", "HTTP Request"),
                    ("evaluation", "Evaluation"),
                    ("gate", "Gate"),
                    ("schedule_execution", "Schedule Execution"),
                ],
                db_column="STEP_TYPE",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="RunnableStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                ("step_order", models.IntegerField(db_column="STEP_ORDER")),
                ("step_type", models.CharField(db_column="STEP_TYPE", max_length=50)),
                ("priority", models.IntegerField(db_column="PRIORITY", default=0)),
                (
                    "eligible_at",
                    models.DateTimeField(auto_now_add=True, db_column="ELIGIBLE_AT"),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(blank=True, db_column="CLAIMED_AT", null=True),
                ),
                (
                    "claimed_by",
                    models.CharField(
                        blank=True, db_column="CLAIMED_BY", max_length=255, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CREATED_AT"),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        db_column="EXECUTION_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runnable_steps",
                        to="executions.execution",
                    ),
                ),
                (
                    "execution_step",
                    models.OneToOneField(
                        db_column="EXECUTION_STEP_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runnable_entry",
                        to="executions.executionstep",
                    ),
                ),
            ],
            options={
                "db_table": "RUNNABLE_STEPS",
                "ordering": ["-priority", "eligible_at"],
                "indexes": [
                    models.Index(
                        fields=["claimed_at", "-priority", "eligible_at"],
                        name="idx_runnable_unclaimed",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("EXECUTION_STATUS_CHANGED", "Execution Status Changed"),
                            ("STEP_STATUS_CHANGED", "Step Status Changed"),
                            ("STEP_OUTPUT_UPDATED", "Step Output Updated"),
                            ("STEP_STARTED", "Step Started"),
                            ("STEP_COMPLETED", "Step Completed"),
                            ("STEP_FAILED", "Step Failed"),
                            ("APPROVAL_REQUESTED", "Approval Requested"),
                            ("APPROVAL_GRANTED", "Approval Granted"),
                            ("APPROVAL_REJECTED", "Approval Rejected"),
                            ("TARGET_ADDED", "Target Added"),
                            ("EXECUTION_COMPLETED", "Execution Completed"),
                            ("EXECUTION_FAILED", "Execution Failed"),
                        ],
                        db_column="EVENT_TYPE",
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("execution", "Execution"),
                            ("execution_step", "Execution Step"),
                            ("execution_target", "Execution Target"),
                        ],
                        db_column="ENTITY_TYPE",
                        max_length=30,
                    ),
                ),
                ("entity_id", models.BigIntegerField(db_column="ENTITY_ID")),
                ("sequence_num", models.BigIntegerField(db_column="SEQUENCE_NUM")),
                (
                    "payload",
                    models.TextField(blank=True, db_column="PAYLOAD", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CREATED_AT"),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        db_column="EXECUTION_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_events",
                        to="executions.execution",
                    ),
                ),
            ],
            options={
                "db_table": "WORKFLOW_EVENTS",
                "ordering": ["execution", "sequence_num"],
                "indexes": [
                    models.Index(
                        fields=["execution", "created_at"],
                        name="idx_wf_events_exec_created",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="idx_wf_events_entity"
                    ),
                ],
                "unique_together": {("execution", "sequence_num")},
            },
        ),
    ]
