# Generated by Django 5.2.12 on 2026-03-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0010_add_workflow_events_and_runnable_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionstep",
            name="config_step_id",
            field=models.CharField(
                blank=True, db_column="CONFIG_STEP_ID", max_length=255, null=True
            ),
        ),
    ]
