# Generated by Django 5.2.12
# V118: rejected_by, rejected_at for gate rejection audit trail (ADR-007)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0011_add_config_step_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionstep",
            name="rejected_at",
            field=models.DateTimeField(blank=True, db_column="REJECTED_AT", null=True),
        ),
        migrations.AddField(
            model_name="executionstep",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                db_column="REJECTED_BY",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_steps",
                to="idp_auth.user",
            ),
        ),
    ]
