# Generated by Django 5.2.12 on 2026-03-13 14:28
#
# DUAL-ENVIRONMENT NOTE (Story 78.1):
# - Tests (SQLite) : Django crée la table WORKFLOW_EVENT_COUNTER via cette migration.
# - Production (Oracle) : La table est créée par Flyway V122__create_workflow_event_counter.sql.
#   → En production, marquer cette migration comme appliquée SANS l'exécuter :
#       python manage.py migrate executions 0015_add_workfloweventcounter --fake

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0014_add_updated_at_to_execution"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowEventCounter",
            fields=[
                (
                    "execution",
                    models.OneToOneField(
                        db_column="EXECUTION_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="event_counter",
                        serialize=False,
                        to="executions.execution",
                    ),
                ),
                (
                    "last_sequence_num",
                    models.BigIntegerField(db_column="LAST_SEQUENCE_NUM", default=0),
                ),
            ],
            options={
                "db_table": "WORKFLOW_EVENT_COUNTER",
            },
        ),
    ]
