# Generated by Django 5.2.12 on 2026-03-13
#
# DUAL-ENVIRONMENT NOTE (Story 78.2):
# - Tests (SQLite) : Django crée les colonnes via cette migration.
# - Production (Oracle) : Les colonnes sont ajoutées par Flyway V123__harden_runnable_steps_with_leases.sql.
#   → En production, marquer cette migration comme appliquée SANS l'exécuter :
#       python manage.py migrate executions 0016_harden_runnable_steps_with_leases --fake

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0015_add_workfloweventcounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="runnablestep",
            name="claimed_until",
            field=models.DateTimeField(
                blank=True, db_column="CLAIMED_UNTIL", null=True
            ),
        ),
        migrations.AddField(
            model_name="runnablestep",
            name="attempt_no",
            field=models.IntegerField(db_column="ATTEMPT_NO", default=0),
        ),
        migrations.AddField(
            model_name="runnablestep",
            name="last_error",
            field=models.TextField(
                blank=True, db_column="LAST_ERROR", null=True
            ),
        ),
        migrations.AddField(
            model_name="runnablestep",
            name="max_attempts",
            field=models.IntegerField(db_column="MAX_ATTEMPTS", default=3),
        ),
        migrations.RemoveIndex(
            model_name="runnablestep",
            name="idx_runnable_unclaimed",
        ),
        migrations.AddIndex(
            model_name="runnablestep",
            index=models.Index(
                fields=["eligible_at", "claimed_until", "-priority"],
                name="idx_runnable_steps_lease",
            ),
        ),
    ]
