# Generated by Django 5.2.12 on 2026-03-13 17:44
# Story 78.7 review: separated from outbox migration for cleaner history.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0018_add_workflow_command"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowcommand",
            name="id",
            field=models.BigAutoField(
                db_column="ID", primary_key=True, serialize=False
            ),
        ),
    ]
