# Generated by Django 5.2.12 on 2026-03-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0019_fix_workflow_command_id_db_column"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(db_column="EVENT_TYPE", max_length=50)),
                (
                    "payload",
                    models.JSONField(blank=True, db_column="PAYLOAD", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("dispatched", "Dispatché"),
                            ("failed", "Échoué"),
                        ],
                        db_column="STATUS",
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_column="IDEMPOTENCY_KEY", max_length=255, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CREATED_AT"),
                ),
                (
                    "dispatched_at",
                    models.DateTimeField(
                        blank=True, db_column="DISPATCHED_AT", null=True
                    ),
                ),
                ("attempt_no", models.IntegerField(db_column="ATTEMPT_NO", default=0)),
                (
                    "max_attempts",
                    models.IntegerField(db_column="MAX_ATTEMPTS", default=3),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, db_column="LAST_ERROR", null=True),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        db_column="EXECUTION_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_entries",
                        to="executions.execution",
                    ),
                ),
            ],
            options={
                "db_table": "EXECUTION_OUTBOX",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="idx_outbox_status_created",
                    )
                ],
            },
        ),
    ]
