-- V001: Create USERS table
-- Story 1.1 - Initialisation du monorepo

CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1;

CREATE TABLE USERS (
    ID              NUMBER DEFAULT SEQ_USERS.NEXTVAL PRIMARY KEY,
    USERNAME        VARCHAR2(255) NOT NULL,
    DISPLAY_NAME    VARCHAR2(255),
    PROFILE         VARCHAR2(50) NOT NULL,
    SAML_SUBJECT    VARCHAR2(512),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UK_USERS_USERNAME ON USERS(USERNAME);
