-- V004: Create AUDIT_LOG table
-- Story 2.4 - Publier et gerer le cycle de vie d'une action
-- FR30: Audit trail for all action modifications

-- Sequence for auto-increment ID
CREATE SEQUENCE SEQ_AUDIT_LOG START WITH 1 INCREMENT BY 1;

-- Audit log table (append-only)
CREATE TABLE AUDIT_LOG (
    ID              NUMBER DEFAULT SEQ_AUDIT_LOG.NEXTVAL PRIMARY KEY,
    TIMESTAMP       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    USER_ID         VARCHAR2(100) NOT NULL,
    ACTION_TYPE     VARCHAR2(50) NOT NULL,
    ENTITY_TYPE     VARCHAR2(50) NOT NULL,
    ENTITY_ID       NUMBER NOT NULL,
    DETAILS         CLOB,
    IP_ADDRESS      VARCHAR2(45),

    -- Constraints
    CONSTRAINT CK_AUDIT_LOG_ACTION_TYPE CHECK (
        ACTION_TYPE IN ('ACTION_CREATED', 'ACTION_UPDATED', 'ACTION_PUBLISHED', 'ACTION_DISABLED', 'ACTION_ENABLED')
    ),
    CONSTRAINT CK_AUDIT_LOG_ENTITY_TYPE CHECK (
        ENTITY_TYPE IN ('action', 'user', 'permission')
    )
);

-- Indexes for common queries
CREATE INDEX IDX_AUDIT_LOG_TIMESTAMP ON AUDIT_LOG(TIMESTAMP);
CREATE INDEX IDX_AUDIT_LOG_ENTITY ON AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_AUDIT_LOG_USER ON AUDIT_LOG(USER_ID);
CREATE INDEX IDX_AUDIT_LOG_ACTION_TYPE ON AUDIT_LOG(ACTION_TYPE);

-- Column comments
COMMENT ON TABLE AUDIT_LOG IS 'Append-only audit log. No UPDATE or DELETE allowed.';
COMMENT ON COLUMN AUDIT_LOG.DETAILS IS 'JSON object with additional context. Example: {"action_name": "Create PDB", "previous_status": "draft", "new_status": "published"}';

-- Update SCHEMA_VERSION with V004 (idempotent MERGE)
MERGE INTO SCHEMA_VERSION D
USING (SELECT 'V004' AS V FROM DUAL) S ON (D.VERSION = S.V)
WHEN NOT MATCHED THEN INSERT (VERSION) VALUES (S.V);
