-- V005: Create USER_PERMISSIONS table
-- Story 1.3 - Profil RBAC et Navigation du Portail

CREATE TABLE USER_PERMISSIONS (
    USER_ID         NUMBER NOT NULL,
    ACTION_ID       NUMBER NOT NULL,
    ENVIRONMENT     VARCHAR2(20) NOT NULL,
    GRANTED_BY      NUMBER,
    GRANTED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_PERMISSIONS PRIMARY KEY (USER_ID, ACTION_ID, ENVIRONMENT),
    CONSTRAINT FK_USER_PERM_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT CK_USER_PERM_ENV CHECK (ENVIRONMENT IN ('DEV', 'QA', 'PROD'))
);

CREATE INDEX IDX_USER_PERM_USER ON USER_PERMISSIONS(USER_ID);
CREATE INDEX IDX_USER_PERM_ACTION ON USER_PERMISSIONS(ACTION_ID);
