-- V007: Create TAGS and ACTION_TAGS tables (Story 2.6, FR11c)
-- Tags flexibles pour les actions : TAGS (id, name, created_at), ACTION_TAGS (action_id, tag_id)

-- Tags table: unique name (normalized lowercase, no spaces) (Story 2.20: identity column)
CREATE TABLE TAGS (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME            VARCHAR2(255) NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_TAGS_NAME UNIQUE (NAME)
);
-- IDX on NAME non nécessaire : Oracle crée déjà un index pour UNIQUE(NAME).

-- Junction table: action <-> tags (many-to-many)
CREATE TABLE ACTION_TAGS (
    ACTION_ID       NUMBER NOT NULL,
    TAG_ID          NUMBER NOT NULL,
    CONSTRAINT PK_ACTION_TAGS PRIMARY KEY (ACTION_ID, TAG_ID),
    CONSTRAINT FK_ACTION_TAGS_ACTION FOREIGN KEY (ACTION_ID) REFERENCES ACTIONS_CATALOG(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACTION_TAGS_TAG FOREIGN KEY (TAG_ID) REFERENCES TAGS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ACTION_TAGS_ACTION ON ACTION_TAGS(ACTION_ID);
CREATE INDEX IDX_ACTION_TAGS_TAG ON ACTION_TAGS(TAG_ID);
