-- V010: Create PROFILES table (Story 2.9 - Gestion des profils dynamiques, FR25a)
-- Profiles dynamiques avec mapping vers groupe AD. Permissions par profil en 2.10–2.12.

CREATE TABLE PROFILES (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    AD_GROUP    VARCHAR2(512) NOT NULL,
    IS_ADMIN    NUMBER(1) DEFAULT 0 NOT NULL,
    IS_AUDITOR  NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT UK_PROFILES_NAME UNIQUE (NAME),
    CONSTRAINT CK_PROFILES_IS_ADMIN   CHECK (IS_ADMIN IN (0, 1)),
    CONSTRAINT CK_PROFILES_IS_AUDITOR CHECK (IS_AUDITOR IN (0, 1))
);

CREATE INDEX IDX_PROFILES_NAME ON PROFILES(NAME);
CREATE INDEX IDX_PROFILES_AD_GROUP ON PROFILES(AD_GROUP);

COMMENT ON COLUMN PROFILES.AD_GROUP IS 'Groupe AD associe au profil (ex. GRP-IDP-ASSURANCE). Mapping pour permissions granulaires (2.10–2.12).';
