-- V011: Create PROFILE_ACTION_PERMISSIONS table (Story 2.10 - Permissions actions par profil)
-- Une ligne par profil : type (LIST/PATTERN/ALL), action_ids/tag_patterns/envs en JSON (CLOB).

CREATE TABLE PROFILE_ACTION_PERMISSIONS (
    PROFILE_ID         NUMBER NOT NULL,
    PERMISSION_TYPE    VARCHAR2(20) NOT NULL,
    ACTION_IDS_JSON    CLOB,
    TAG_PATTERNS_JSON  CLOB,
    ENVIRONMENTS_JSON  CLOB,
    CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_PROFILE_ACTION_PERMISSIONS PRIMARY KEY (PROFILE_ID),
    CONSTRAINT FK_PROFILE_ACTION_PERM_PROFILE FOREIGN KEY (PROFILE_ID) REFERENCES PROFILES(ID) ON DELETE CASCADE,
    CONSTRAINT CK_PROFILE_ACTION_PERM_TYPE CHECK (PERMISSION_TYPE IN ('LIST', 'PATTERN', 'ALL'))
);

-- Note: No explicit index needed on PROFILE_ID as PRIMARY KEY already creates one.

COMMENT ON COLUMN PROFILE_ACTION_PERMISSIONS.PERMISSION_TYPE IS 'LIST=actions specifiques, PATTERN=par tags, ALL=toutes';
COMMENT ON COLUMN PROFILE_ACTION_PERMISSIONS.ACTION_IDS_JSON IS 'JSON array of action IDs when PERMISSION_TYPE=LIST, e.g. [1,2,3]';
COMMENT ON COLUMN PROFILE_ACTION_PERMISSIONS.TAG_PATTERNS_JSON IS 'JSON array of tag names when PERMISSION_TYPE=PATTERN, e.g. ["oracle","provisioning"]';
COMMENT ON COLUMN PROFILE_ACTION_PERMISSIONS.ENVIRONMENTS_JSON IS 'JSON array of allowed environments, e.g. ["DEV","STAGING","PROD"]';

-- Task 1.2: Update SCHEMA_VERSION (idempotent MERGE). Execute after V010.
MERGE INTO SCHEMA_VERSION D
USING (SELECT 'V011' AS V FROM DUAL) S ON (D.VERSION = S.V)
WHEN NOT MATCHED THEN INSERT (VERSION) VALUES (S.V);
