-- V012: Create PROFILE_TARGET_PERMISSIONS table (Story 2.11 - Permissions targets par profil)
-- Une ligne par profil : type (LIST/PATTERN/ALL), target_names/target_patterns en JSON (CLOB).

CREATE TABLE PROFILE_TARGET_PERMISSIONS (
    PROFILE_ID         NUMBER NOT NULL,
    PERMISSION_TYPE    VARCHAR2(20) NOT NULL,
    TARGET_NAMES_JSON  CLOB,
    TARGET_PATTERNS_JSON CLOB,
    CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_PROFILE_TARGET_PERMISSIONS PRIMARY KEY (PROFILE_ID),
    CONSTRAINT FK_PROFILE_TARGET_PERM_PROFILE FOREIGN KEY (PROFILE_ID) REFERENCES PROFILES(ID) ON DELETE CASCADE,
    CONSTRAINT CK_PROFILE_TARGET_PERM_TYPE CHECK (PERMISSION_TYPE IN ('LIST', 'PATTERN', 'ALL'))
);

COMMENT ON COLUMN PROFILE_TARGET_PERMISSIONS.PERMISSION_TYPE IS 'LIST=targets explicites, PATTERN=ex. assurance-*, ALL=tous';
COMMENT ON COLUMN PROFILE_TARGET_PERMISSIONS.TARGET_NAMES_JSON IS 'JSON array of target names when PERMISSION_TYPE=LIST, e.g. ["assurance-db01","assurance-db02"]';
COMMENT ON COLUMN PROFILE_TARGET_PERMISSIONS.TARGET_PATTERNS_JSON IS 'JSON array of fnmatch patterns when PERMISSION_TYPE=PATTERN, e.g. ["assurance-*","infra-*"]';
