-- V021: Create USER_FAVORITES table
-- Story 3.1 AC14: Favoris utilisateur (user_id, action_id, created_at)

CREATE TABLE USER_FAVORITES (
    USER_ID     NUMBER NOT NULL,
    ACTION_ID   NUMBER NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_USER_FAVORITES PRIMARY KEY (USER_ID, ACTION_ID),
    CONSTRAINT FK_USER_FAVORITES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_FAVORITES_ACTION FOREIGN KEY (ACTION_ID) REFERENCES ACTIONS_CATALOG(ID) ON DELETE CASCADE
);

-- Index for efficient lookup by user_id (AC14)
CREATE INDEX IDX_USER_FAVORITES_USER_ID ON USER_FAVORITES(USER_ID);

COMMENT ON TABLE USER_FAVORITES IS 'Favoris utilisateur (Story 3.1 AC14). Un utilisateur peut marquer des actions comme favorites.';
COMMENT ON COLUMN USER_FAVORITES.USER_ID IS 'ID de l''utilisateur (FK vers USERS)';
COMMENT ON COLUMN USER_FAVORITES.ACTION_ID IS 'ID de l''action favorite (FK vers ACTIONS_CATALOG)';
COMMENT ON COLUMN USER_FAVORITES.CREATED_AT IS 'Date d''ajout aux favoris';
