-- V036: Add INTEGRATION_ID column to ACTIONS_CATALOG (Story 9.11)
-- Bug fix: ACTION_EXECUTION_CONFIG table doesn't exist, integration should be linked directly to action
-- Allows JOIN between ACTIONS_CATALOG and INTEGRATIONS for execution queries

-- Add INTEGRATION_ID column if it doesn't exist
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tab_columns
  WHERE table_name = 'ACTIONS_CATALOG' AND column_name = 'INTEGRATION_ID';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ACTIONS_CATALOG ADD INTEGRATION_ID NUMBER';
    EXECUTE IMMEDIATE 'ALTER TABLE ACTIONS_CATALOG ADD CONSTRAINT FK_ACTIONS_CATALOG_INTEGRATION 
                       FOREIGN KEY (INTEGRATION_ID) REFERENCES INTEGRATIONS(ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_ACTIONS_CATALOG_INTEGRATION_ID ON ACTIONS_CATALOG(INTEGRATION_ID)';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN ACTIONS_CATALOG.INTEGRATION_ID IS ''FK to INTEGRATIONS - Platform integration configuration for execution (Story 9.11)''';
  END IF;
END;
/
