-- V042: Add surrogate ID to ACTION_TAGS for Django ORM compatibility
-- Django expects a single-column primary key on through tables; our original V007 used a composite PK (ACTION_ID, TAG_ID).
-- Adding an identity ID column keeps existing semantics (unique ACTION_ID+TAG_ID) while enabling ORM prefetch/Count().

-- 1) Add identity column (populate existing rows later)
ALTER TABLE ACTION_TAGS ADD (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
);

-- 2) Backfill ID for existing rows (identity default on update)
UPDATE ACTION_TAGS SET ID = DEFAULT WHERE ID IS NULL;

-- 4) Replace composite PK with surrogate PK (keep uniqueness constraint)
ALTER TABLE ACTION_TAGS DROP CONSTRAINT PK_ACTION_TAGS;
ALTER TABLE ACTION_TAGS ADD CONSTRAINT PK_ACTION_TAGS PRIMARY KEY (ID);
ALTER TABLE ACTION_TAGS ADD CONSTRAINT UK_ACTION_TAGS_ACTION_TAG UNIQUE (ACTION_ID, TAG_ID);
