-- V048: Convert TIMESTAMP WITH TIME ZONE to TIMESTAMP (plain)
-- Purpose: Compatibility with oracledb thin mode (DPY-3022: named time zones not supported)
-- Convention: All timestamps stored in UTC.
--
-- ORA-01439: Oracle requires column to be empty to modify type. Use add/copy/drop/rename pattern.

ALTER SESSION SET TIME_ZONE = 'UTC';

-- =============================================================================
-- EXECUTIONS
-- =============================================================================

ALTER TABLE EXECUTIONS ADD (STARTED_AT_NEW TIMESTAMP);
UPDATE EXECUTIONS SET STARTED_AT_NEW = STARTED_AT;
ALTER TABLE EXECUTIONS DROP COLUMN STARTED_AT;
ALTER TABLE EXECUTIONS RENAME COLUMN STARTED_AT_NEW TO STARTED_AT;

ALTER TABLE EXECUTIONS ADD (COMPLETED_AT_NEW TIMESTAMP);
UPDATE EXECUTIONS SET COMPLETED_AT_NEW = COMPLETED_AT;
ALTER TABLE EXECUTIONS DROP COLUMN COMPLETED_AT;
ALTER TABLE EXECUTIONS RENAME COLUMN COMPLETED_AT_NEW TO COMPLETED_AT;

ALTER TABLE EXECUTIONS ADD (CREATED_AT_NEW TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
UPDATE EXECUTIONS SET CREATED_AT_NEW = CREATED_AT;
ALTER TABLE EXECUTIONS DROP COLUMN CREATED_AT;
ALTER TABLE EXECUTIONS RENAME COLUMN CREATED_AT_NEW TO CREATED_AT;

ALTER TABLE EXECUTIONS ADD (APPROVED_AT_NEW TIMESTAMP);
UPDATE EXECUTIONS SET APPROVED_AT_NEW = APPROVED_AT;
ALTER TABLE EXECUTIONS DROP COLUMN APPROVED_AT;
ALTER TABLE EXECUTIONS RENAME COLUMN APPROVED_AT_NEW TO APPROVED_AT;

-- =============================================================================
-- EXECUTION_STEPS
-- =============================================================================

ALTER TABLE EXECUTION_STEPS ADD (STARTED_AT_NEW TIMESTAMP);
UPDATE EXECUTION_STEPS SET STARTED_AT_NEW = STARTED_AT;
ALTER TABLE EXECUTION_STEPS DROP COLUMN STARTED_AT;
ALTER TABLE EXECUTION_STEPS RENAME COLUMN STARTED_AT_NEW TO STARTED_AT;

ALTER TABLE EXECUTION_STEPS ADD (COMPLETED_AT_NEW TIMESTAMP);
UPDATE EXECUTION_STEPS SET COMPLETED_AT_NEW = COMPLETED_AT;
ALTER TABLE EXECUTION_STEPS DROP COLUMN COMPLETED_AT;
ALTER TABLE EXECUTION_STEPS RENAME COLUMN COMPLETED_AT_NEW TO COMPLETED_AT;

ALTER TABLE EXECUTION_STEPS ADD (CREATED_AT_NEW TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
UPDATE EXECUTION_STEPS SET CREATED_AT_NEW = CREATED_AT;
ALTER TABLE EXECUTION_STEPS DROP COLUMN CREATED_AT;
ALTER TABLE EXECUTION_STEPS RENAME COLUMN CREATED_AT_NEW TO CREATED_AT;

-- =============================================================================
-- SCHEDULED_EXECUTIONS
-- =============================================================================

ALTER TABLE SCHEDULED_EXECUTIONS ADD (SCHEDULED_AT_NEW TIMESTAMP);
UPDATE SCHEDULED_EXECUTIONS SET SCHEDULED_AT_NEW = SCHEDULED_AT;
ALTER TABLE SCHEDULED_EXECUTIONS DROP COLUMN SCHEDULED_AT;
ALTER TABLE SCHEDULED_EXECUTIONS RENAME COLUMN SCHEDULED_AT_NEW TO SCHEDULED_AT;

ALTER TABLE SCHEDULED_EXECUTIONS ADD (CREATED_AT_NEW TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
UPDATE SCHEDULED_EXECUTIONS SET CREATED_AT_NEW = CREATED_AT;
ALTER TABLE SCHEDULED_EXECUTIONS DROP COLUMN CREATED_AT;
ALTER TABLE SCHEDULED_EXECUTIONS RENAME COLUMN CREATED_AT_NEW TO CREATED_AT;

ALTER TABLE SCHEDULED_EXECUTIONS ADD (UPDATED_AT_NEW TIMESTAMP);
UPDATE SCHEDULED_EXECUTIONS SET UPDATED_AT_NEW = UPDATED_AT;
ALTER TABLE SCHEDULED_EXECUTIONS DROP COLUMN UPDATED_AT;
ALTER TABLE SCHEDULED_EXECUTIONS RENAME COLUMN UPDATED_AT_NEW TO UPDATED_AT;

-- =============================================================================
-- RECURRING_PATTERNS
-- =============================================================================

ALTER TABLE RECURRING_PATTERNS ADD (NEXT_EXECUTION_DATE_NEW TIMESTAMP);
UPDATE RECURRING_PATTERNS SET NEXT_EXECUTION_DATE_NEW = NEXT_EXECUTION_DATE;
ALTER TABLE RECURRING_PATTERNS MODIFY (NEXT_EXECUTION_DATE_NEW NOT NULL);
ALTER TABLE RECURRING_PATTERNS DROP COLUMN NEXT_EXECUTION_DATE;
ALTER TABLE RECURRING_PATTERNS RENAME COLUMN NEXT_EXECUTION_DATE_NEW TO NEXT_EXECUTION_DATE;

ALTER TABLE RECURRING_PATTERNS ADD (CREATED_AT_NEW TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
UPDATE RECURRING_PATTERNS SET CREATED_AT_NEW = CREATED_AT;
ALTER TABLE RECURRING_PATTERNS DROP COLUMN CREATED_AT;
ALTER TABLE RECURRING_PATTERNS RENAME COLUMN CREATED_AT_NEW TO CREATED_AT;

ALTER TABLE RECURRING_PATTERNS ADD (UPDATED_AT_NEW TIMESTAMP);
UPDATE RECURRING_PATTERNS SET UPDATED_AT_NEW = UPDATED_AT;
ALTER TABLE RECURRING_PATTERNS DROP COLUMN UPDATED_AT;
ALTER TABLE RECURRING_PATTERNS RENAME COLUMN UPDATED_AT_NEW TO UPDATED_AT;

-- Comments
COMMENT ON COLUMN EXECUTIONS.CREATED_AT IS 'UTC timestamp (plain TIMESTAMP). Convention: all timestamps in UTC';
COMMENT ON COLUMN SCHEDULED_EXECUTIONS.SCHEDULED_AT IS 'UTC timestamp (plain TIMESTAMP). Convention: all timestamps in UTC';
COMMENT ON COLUMN RECURRING_PATTERNS.NEXT_EXECUTION_DATE IS 'UTC timestamp (plain TIMESTAMP). Convention: all timestamps in UTC';
