-- V049: Create REF_ENGINES table (Story 13.7)
-- Technologies (engines) are now managed via reference table instead of CHECK constraints
-- This allows DBOPS to manage engines without code changes

-- Create REF_ENGINES reference table
CREATE TABLE REF_ENGINES (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE            VARCHAR2(50) NOT NULL,
    LABEL           VARCHAR2(100) NOT NULL,
    DISPLAY_ORDER   NUMBER DEFAULT 0 NOT NULL,
    IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL,
    
    CONSTRAINT UK_REF_ENGINES_CODE UNIQUE (CODE),
    CONSTRAINT CK_REF_ENGINES_IS_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- Index for active engines queries
CREATE INDEX IDX_REF_ENGINES_IS_ACTIVE ON REF_ENGINES(IS_ACTIVE);
CREATE INDEX IDX_REF_ENGINES_DISPLAY_ORDER ON REF_ENGINES(DISPLAY_ORDER);

-- Comments
COMMENT ON TABLE REF_ENGINES IS 'Reference table for database engines/technologies. Managed by DBOPS via admin interface.';
COMMENT ON COLUMN REF_ENGINES.CODE IS 'Unique code identifier (e.g., Oracle, SQL Server, DB2)';
COMMENT ON COLUMN REF_ENGINES.LABEL IS 'Display label (can be same as CODE)';
COMMENT ON COLUMN REF_ENGINES.DISPLAY_ORDER IS 'Order for display in dropdowns/lists';
COMMENT ON COLUMN REF_ENGINES.IS_ACTIVE IS '1 = active, 0 = inactive (soft delete)';

-- Insert current engine values
INSERT INTO REF_ENGINES (CODE, LABEL, DISPLAY_ORDER, IS_ACTIVE) VALUES ('Oracle', 'Oracle', 1, 1);
INSERT INTO REF_ENGINES (CODE, LABEL, DISPLAY_ORDER, IS_ACTIVE) VALUES ('SQL Server', 'SQL Server', 2, 1);
INSERT INTO REF_ENGINES (CODE, LABEL, DISPLAY_ORDER, IS_ACTIVE) VALUES ('DB2', 'DB2', 3, 1);
INSERT INTO REF_ENGINES (CODE, LABEL, DISPLAY_ORDER, IS_ACTIVE) VALUES ('PostgreSQL', 'PostgreSQL', 4, 1);
INSERT INTO REF_ENGINES (CODE, LABEL, DISPLAY_ORDER, IS_ACTIVE) VALUES ('MySQL', 'MySQL', 5, 1);
INSERT INTO REF_ENGINES (CODE, LABEL, DISPLAY_ORDER, IS_ACTIVE) VALUES ('Workflow', 'Workflow', 6, 1);
