-- V058: Add ACTION_DEACTIVATED and ACTION_REACTIVATED to AUDIT_LOG ACTION_TYPE (Story 18.1)
-- Required for soft-delete (désactivation) and reactivation audit trail

ALTER TABLE AUDIT_LOG DROP CONSTRAINT CK_AUDIT_LOG_ACTION_TYPE;

ALTER TABLE AUDIT_LOG ADD CONSTRAINT CK_AUDIT_LOG_ACTION_TYPE CHECK (
    ACTION_TYPE IN (
        -- Action lifecycle
        'ACTION_CREATED', 'ACTION_UPDATED', 'ACTION_PUBLISHED',
        'ACTION_DISABLED', 'ACTION_ENABLED', 'ACTION_DELETED',
        'ACTION_DEACTIVATED', 'ACTION_REACTIVATED',

        -- Profile lifecycle
        'PROFILE_CREATED', 'PROFILE_UPDATED', 'PROFILE_DELETED',

        -- Integration lifecycle
        'INTEGRATION_CREATED', 'INTEGRATION_UPDATED', 'INTEGRATION_DELETED',

        -- Execution lifecycle (support both legacy STARTED and current RUNNING naming)
        'EXECUTION_SUBMITTED', 'EXECUTION_STARTED', 'EXECUTION_RUNNING',
        'EXECUTION_COMPLETED', 'EXECUTION_FAILED', 'EXECUTION_CANCELLED',
        'EXECUTION_PENDING_APPROVAL', 'EXECUTION_APPROVED', 'EXECUTION_REJECTED',
        'EXECUTION_TARGET_FORBIDDEN',

        -- ServiceNow change
        'SERVICENOW_CHANGE_CREATED',

        -- Remediation / auto-remediation
        'REMEDIATION_EXECUTION_CREATED',
        'AUTO_REMEDIATION_TRIGGERED', 'AUTO_REMEDIATION_SUCCESS', 'AUTO_REMEDIATION_FAILED',

        -- Scheduled executions
        'SCHEDULED_EXECUTION_CREATED', 'SCHEDULED_EXECUTION_RECURRING_CREATED',
        'SCHEDULED_EXECUTION_EXECUTED', 'SCHEDULED_EXECUTION_CANCELLED',
        'SCHEDULED_EXECUTION_RECURRING_DISABLED',

        -- User / Auth / Favorites
        'USER_CREATED', 'USER_UPDATED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_REFRESH',
        'FAVORITE_ADDED', 'FAVORITE_REMOVED'
    )
);

COMMENT ON COLUMN AUDIT_LOG.ACTION_TYPE IS 'Story 18.1 V058: ACTION_DEACTIVATED, ACTION_REACTIVATED added for soft-delete audit trail';
