-- V061: Create INTEGRATION_TYPE_CATALOGUE and INTEGRATION_ACTIONS tables
-- Story 24.1: Formal catalogue of integration types and actions (AAP, ServiceNow, etc.)
-- Enables validation of INTEGRATIONS against supported types and action params (JSON Schema)

-- 1. Integration type catalogue (code = primary key, e.g. aap, servicenow)
CREATE TABLE INTEGRATION_TYPE_CATALOGUE (
    CODE         VARCHAR2(50) PRIMARY KEY,
    NAME         VARCHAR2(255) NOT NULL,
    DESCRIPTION  CLOB DEFAULT '',
    VERSION      VARCHAR2(20) DEFAULT '1.0' NOT NULL,
    IS_ACTIVE    NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_INTEGRATION_TYPE_CATALOGUE_IS_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE INDEX IDX_INTEGRATION_TYPE_CATALOGUE_IS_ACTIVE ON INTEGRATION_TYPE_CATALOGUE(IS_ACTIVE);

COMMENT ON TABLE INTEGRATION_TYPE_CATALOGUE IS 'Formal catalogue of supported integration types (Story 24.1). Defines AAP, ServiceNow, etc. with metadata.';
COMMENT ON COLUMN INTEGRATION_TYPE_CATALOGUE.CODE IS 'Primary key, e.g. aap, servicenow, terraform';
COMMENT ON COLUMN INTEGRATION_TYPE_CATALOGUE.NAME IS 'Display name';
COMMENT ON COLUMN INTEGRATION_TYPE_CATALOGUE.DESCRIPTION IS 'Optional description';
COMMENT ON COLUMN INTEGRATION_TYPE_CATALOGUE.VERSION IS 'Catalogue version';
COMMENT ON COLUMN INTEGRATION_TYPE_CATALOGUE.IS_ACTIVE IS '1 = active, 0 = inactive';

-- 2. Actions per integration type (required/optional params as JSON Schema in CLOB)
CREATE TABLE INTEGRATION_ACTIONS (
    ID                    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INTEGRATION_TYPE_CODE VARCHAR2(50) NOT NULL,
    ACTION_CODE           VARCHAR2(100) NOT NULL,
    ACTION_LABEL          VARCHAR2(255) NOT NULL,
    DESCRIPTION           CLOB DEFAULT '',
    REQUIRED_PARAMS       CLOB DEFAULT '{}',
    OPTIONAL_PARAMS       CLOB DEFAULT '{}',
    RESPONSE_FORMAT       CLOB DEFAULT '{}',
    IS_ACTIVE             NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_INTEGRATION_ACTIONS_TYPE FOREIGN KEY (INTEGRATION_TYPE_CODE) REFERENCES INTEGRATION_TYPE_CATALOGUE(CODE) ON DELETE CASCADE,
    CONSTRAINT UK_INTEGRATION_ACTIONS_TYPE_CODE UNIQUE (INTEGRATION_TYPE_CODE, ACTION_CODE),
    CONSTRAINT CK_INTEGRATION_ACTIONS_IS_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE INDEX IDX_INTEGRATION_ACTIONS_TYPE ON INTEGRATION_ACTIONS(INTEGRATION_TYPE_CODE);
CREATE INDEX IDX_INTEGRATION_ACTIONS_IS_ACTIVE ON INTEGRATION_ACTIONS(IS_ACTIVE);

COMMENT ON TABLE INTEGRATION_ACTIONS IS 'Actions supported by each integration type (Story 24.1). Params and response as JSON Schema in CLOB.';
COMMENT ON COLUMN INTEGRATION_ACTIONS.INTEGRATION_TYPE_CODE IS 'FK to INTEGRATION_TYPE_CATALOGUE.CODE';
COMMENT ON COLUMN INTEGRATION_ACTIONS.ACTION_CODE IS 'Action identifier, e.g. start_job, create_change';
COMMENT ON COLUMN INTEGRATION_ACTIONS.REQUIRED_PARAMS IS 'JSON Schema for required parameters';
COMMENT ON COLUMN INTEGRATION_ACTIONS.OPTIONAL_PARAMS IS 'JSON Schema for optional parameters';
COMMENT ON COLUMN INTEGRATION_ACTIONS.RESPONSE_FORMAT IS 'JSON Schema for response format';
