-- V062: Create CORE_FEATURE_FLAGS table
-- Django core/0003_feature_flags - Feature flags for progressive rollout
-- Pattern: standard reference table with identity PK

CREATE TABLE CORE_FEATURE_FLAGS (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FLAG_KEY        VARCHAR2(100) NOT NULL UNIQUE,
    ENABLED         NUMBER(1) DEFAULT 0 NOT NULL,
    ROLLOUT_PERCENT NUMBER(10) DEFAULT 100 NOT NULL,
    DESCRIPTION     VARCHAR2(500) DEFAULT '',
    UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(100) DEFAULT '',
    CONSTRAINT CK_FEATURE_FLAGS_ENABLED CHECK (ENABLED IN (0, 1)),
    CONSTRAINT CK_FEATURE_FLAGS_ROLLOUT CHECK (ROLLOUT_PERCENT BETWEEN 0 AND 100)
);

COMMENT ON TABLE CORE_FEATURE_FLAGS IS 'Feature flags for progressive rollout (Story core/0003). FLAG_KEY is unique identifier.';
COMMENT ON COLUMN CORE_FEATURE_FLAGS.FLAG_KEY IS 'Unique key for the feature flag (e.g. new_workflow_builder)';
COMMENT ON COLUMN CORE_FEATURE_FLAGS.ENABLED IS '1 = enabled, 0 = disabled';
COMMENT ON COLUMN CORE_FEATURE_FLAGS.ROLLOUT_PERCENT IS 'Percentage of users to enable (0-100)';
