-- Story 25.1: Create EXECUTION_TARGETS table
-- Links executions to their targets (servers, databases, etc.)
-- Foundation for condition gates, mutex, and RBAC validation

CREATE TABLE EXECUTION_TARGETS (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EXECUTION_ID NUMBER(19) NOT NULL,
    TARGET_TYPE VARCHAR2(50) NOT NULL,
    TARGET_ID VARCHAR2(200) NOT NULL,
    TARGET_NAME VARCHAR2(255) NOT NULL,
    TARGET_METADATA CLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_EXEC_TARGETS_EXEC FOREIGN KEY (EXECUTION_ID) REFERENCES EXECUTIONS(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_EXEC_TARGETS_EXEC_TYPE_ID UNIQUE (EXECUTION_ID, TARGET_TYPE, TARGET_ID)
);

COMMENT ON TABLE EXECUTION_TARGETS IS 'Explicit link between executions and their targets (Story 25.1)';
COMMENT ON COLUMN EXECUTION_TARGETS.TARGET_TYPE IS 'Type of target: SERVER, DATABASE, INSTANCE, SCHEMA, CLUSTER, OTHER';
COMMENT ON COLUMN EXECUTION_TARGETS.TARGET_ID IS 'Opaque identifier from inventory (target name)';
COMMENT ON COLUMN EXECUTION_TARGETS.TARGET_NAME IS 'Snapshot of target name for display (immutable after creation)';
COMMENT ON COLUMN EXECUTION_TARGETS.TARGET_METADATA IS 'JSON snapshot of target metadata at execution time (environment, technology, etc.)';

-- Forward lookup: "Which targets for this execution?"
CREATE INDEX IDX_EXEC_TARGETS_EXEC ON EXECUTION_TARGETS(EXECUTION_ID);

-- Reverse lookup: "Which executions on this server?"
CREATE INDEX IDX_EXEC_TARGETS_TARGET ON EXECUTION_TARGETS(TARGET_TYPE, TARGET_ID);
