-- Story 25.2: Add WAITING status to EXECUTION_STEPS
-- Adds WAITING to the CHECK constraint on STATUS column
--
-- Rollback (if needed):
-- ALTER TABLE EXECUTION_STEPS DROP CONSTRAINT CK_EXECUTION_STEPS_STATUS;
-- ALTER TABLE EXECUTION_STEPS ADD CONSTRAINT CK_EXECUTION_STEPS_STATUS
-- CHECK (STATUS IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED'));
-- COMMENT ON COLUMN EXECUTION_STEPS.STATUS IS
-- 'Step status: PENDING (queued), RUNNING (in progress), COMPLETED (success), FAILED (error), SKIPPED (skipped due to condition)';

-- Drop existing CHECK constraint on STATUS
ALTER TABLE EXECUTION_STEPS DROP CONSTRAINT CK_EXECUTION_STEPS_STATUS;

-- Add new CHECK constraint with WAITING status
ALTER TABLE EXECUTION_STEPS ADD CONSTRAINT CK_EXECUTION_STEPS_STATUS
CHECK (STATUS IN ('PENDING', 'WAITING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED'));

-- Update comment on STATUS column
COMMENT ON COLUMN EXECUTION_STEPS.STATUS IS
'Step status: PENDING (queued), WAITING (gate conditions not met), RUNNING (in progress), COMPLETED (success), FAILED (error), SKIPPED (skipped due to condition)';
