-- V084: Partition EXECUTIONS table by CREATED_AT (monthly INTERVAL)
-- Story 40.2 - Epic 40: Partitionnement et rétention tables performance
-- Approche: CREATE NEW + MIGRATE DATA + RENAME (fenêtre de maintenance requise)
-- Durée estimée: 8-12h (cf. 40.1 §9)
-- Rollback: see database/rollback/V084__partition_executions_rollback.sql
--
-- PRÉCONDITIONS (§10 note DBA 40.1):
--   - Fenêtre de maintenance planifiée avec DBOPS/infra
--   - Backup base effectué
--   - Script testé sur DEV/PREPROD
--   - Noms des contraintes FK enfant vérifiés (USER_CONSTRAINTS)
--   - Liste complète des colonnes vérifiée (USER_TAB_COLUMNS)
--
-- COLONNES (état après V083) :
--   ID, ACTION_ID, USER_ID, ENVIRONMENT, PARAMETERS, STATUS,
--   SERVICENOW_CHANGE_ID, STARTED_AT, COMPLETED_AT, CREATED_AT (TIMESTAMP, V048),
--   APPROVED_BY, APPROVED_AT, APPROVAL_COMMENT (V030),
--   PARENT_EXECUTION_ID (V033), ERROR_MESSAGE (V057)

-- ============================================================
-- PHASE 0 : Vérification des préconditions (idempotence)
-- ============================================================
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USER_TABLES WHERE TABLE_NAME = 'EXECUTIONS_NEW';
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'EXECUTIONS_NEW already exists - check previous migration state and clean up manually');
    END IF;
    SELECT COUNT(*) INTO v_count
    FROM USER_TABLES WHERE TABLE_NAME = 'EXECUTIONS_OLD';
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20003,
            'EXECUTIONS_OLD already exists - check previous migration state and clean up manually');
    END IF;
    SELECT COUNT(*) INTO v_count
    FROM USER_TABLES WHERE TABLE_NAME = 'EXECUTIONS_MIGRATION_CHECK';
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20004,
            'EXECUTIONS_MIGRATION_CHECK already exists - Phase 1 ran previously but migration did not complete. Clean up manually: DROP TABLE EXECUTIONS_MIGRATION_CHECK PURGE');
    END IF;
END;
/

-- ============================================================
-- PHASE 1 : Snapshot de contrôle (COUNT avant migration)
-- ============================================================
CREATE TABLE EXECUTIONS_MIGRATION_CHECK AS
    SELECT COUNT(*) AS ROW_COUNT FROM EXECUTIONS;

-- ============================================================
-- PHASE 2 : Créer la nouvelle table partitionnée
-- ============================================================
-- Note: Aucune FK ni CHECK inline — ajoutés en Phase 6/9 après renommage
-- Note: IDENTITY séquence recalée en fin de Phase 3
CREATE TABLE EXECUTIONS_NEW (
    ID              NUMBER NOT NULL,
    ACTION_ID       NUMBER NOT NULL,
    USER_ID         NUMBER NOT NULL,
    ENVIRONMENT     VARCHAR2(50) NOT NULL,
    PARAMETERS      CLOB,
    STATUS          VARCHAR2(20) DEFAULT 'SUBMITTED' NOT NULL,
    SERVICENOW_CHANGE_ID VARCHAR2(100),
    STARTED_AT      TIMESTAMP,
    COMPLETED_AT    TIMESTAMP,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    APPROVED_BY     NUMBER(10),
    APPROVED_AT     TIMESTAMP,
    APPROVAL_COMMENT VARCHAR2(1000),
    PARENT_EXECUTION_ID NUMBER(19),
    ERROR_MESSAGE   CLOB,
    CONSTRAINT PK_EXECUTIONS_NEW PRIMARY KEY (ID)  -- Global index (non-partitionné)
)
PARTITION BY RANGE (CREATED_AT)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_BEFORE_2024 VALUES LESS THAN (TIMESTAMP '2024-01-01 00:00:00')
);

-- ============================================================
-- PHASE 3 : Migration des données
-- ============================================================
-- Direct path insert + parallélisation pour performance (cf. 40.1 §8)
INSERT /*+ APPEND PARALLEL(4) */ INTO EXECUTIONS_NEW
    (ID, ACTION_ID, USER_ID, ENVIRONMENT, PARAMETERS, STATUS,
     SERVICENOW_CHANGE_ID, STARTED_AT, COMPLETED_AT, CREATED_AT,
     APPROVED_BY, APPROVED_AT, APPROVAL_COMMENT,
     PARENT_EXECUTION_ID, ERROR_MESSAGE)
SELECT  ID, ACTION_ID, USER_ID, ENVIRONMENT, PARAMETERS, STATUS,
        SERVICENOW_CHANGE_ID, STARTED_AT, COMPLETED_AT, CREATED_AT,
        APPROVED_BY, APPROVED_AT, APPROVAL_COMMENT,
        PARENT_EXECUTION_ID, ERROR_MESSAGE
FROM EXECUTIONS;
COMMIT;

-- Recaler la séquence IDENTITY au-delà du MAX(ID) actuel (point critique 40.2 §Dev Notes)
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(ID), 0) INTO v_max FROM EXECUTIONS_NEW;
    IF v_max > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE EXECUTIONS_NEW MODIFY ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH '
            || (v_max + 1) || ' INCREMENT BY 1 NOCACHE)';
    END IF;
END;
/

-- ============================================================
-- PHASE 4 : Désactiver les FK depuis les tables enfant
-- ============================================================
-- Noms des contraintes à vérifier dans USER_CONSTRAINTS si besoin :
--   SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS
--   WHERE TABLE_NAME IN ('EXECUTION_STEPS','EXECUTION_TARGETS') AND CONSTRAINT_TYPE='R'
ALTER TABLE EXECUTION_STEPS DISABLE CONSTRAINT FK_EXEC_STEPS_EXECUTION;
ALTER TABLE EXECUTION_TARGETS DISABLE CONSTRAINT FK_EXEC_TARGETS_EXECUTION;

-- ============================================================
-- PHASE 5 : Renommage
-- ============================================================
ALTER TABLE EXECUTIONS RENAME TO EXECUTIONS_OLD;
ALTER TABLE EXECUTIONS_NEW RENAME TO EXECUTIONS;
ALTER TABLE EXECUTIONS RENAME CONSTRAINT PK_EXECUTIONS_NEW TO PK_EXECUTIONS;

-- ============================================================
-- PHASE 6 : Recréer les FK applicatives sur EXECUTIONS
-- ============================================================
ALTER TABLE EXECUTIONS ADD CONSTRAINT FK_EXECUTIONS_ACTION
    FOREIGN KEY (ACTION_ID) REFERENCES ACTIONS_CATALOG(ID);

ALTER TABLE EXECUTIONS ADD CONSTRAINT FK_EXECUTIONS_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

ALTER TABLE EXECUTIONS ADD CONSTRAINT FK_EXECUTIONS_APPROVED_BY
    FOREIGN KEY (APPROVED_BY) REFERENCES USERS(ID);

-- Auto-référence DEFERRABLE INITIALLY DEFERRED (facilite les purges futures — 40.5, §3.4 DBA)
ALTER TABLE EXECUTIONS ADD CONSTRAINT FK_EXECUTIONS_PARENT
    FOREIGN KEY (PARENT_EXECUTION_ID) REFERENCES EXECUTIONS(ID) ON DELETE SET NULL
    DEFERRABLE INITIALLY DEFERRED;

-- ============================================================
-- PHASE 7 : Réactiver les FK depuis les tables enfant
-- ============================================================
ALTER TABLE EXECUTION_STEPS ENABLE CONSTRAINT FK_EXEC_STEPS_EXECUTION;
ALTER TABLE EXECUTION_TARGETS ENABLE CONSTRAINT FK_EXEC_TARGETS_EXECUTION;

-- ============================================================
-- PHASE 8 : Recréer les index (locaux prefixed + globaux)
-- ============================================================

-- Anciens index à supprimer (présents dans EXECUTIONS_OLD, non copiés automatiquement)
-- Note: les index sur EXECUTIONS_OLD sont supprimés avec DROP TABLE EXECUTIONS_OLD PURGE en Phase 11
-- Les nouveaux index sont créés directement sur EXECUTIONS (= anciennement EXECUTIONS_NEW)

-- Index locaux prefixed (bénéficient du partition pruning — AC#4 §6.1 DBA)
-- IDX_EXEC_ACTION_CREATED (V063) → recréé comme local prefixed (CREATED_AT, ACTION_ID)
CREATE INDEX IDX_EXECUTIONS_CREATED_ACTION
    ON EXECUTIONS(CREATED_AT, ACTION_ID) LOCAL;

-- IDX_EXECUTIONS_USER_ID (V023) → recréé comme local prefixed (CREATED_AT, USER_ID)
CREATE INDEX IDX_EXECUTIONS_CREATED_USER
    ON EXECUTIONS(CREATED_AT, USER_ID) LOCAL;

-- IDX_EXECUTIONS_STATUS (V023) → recréé comme local prefixed (CREATED_AT, STATUS)
CREATE INDEX IDX_EXECUTIONS_CREATED_STATUS
    ON EXECUTIONS(CREATED_AT, STATUS) LOCAL;

-- Index global sur PARENT_EXECUTION_ID (partition key non incluse → obligatoirement global)
CREATE INDEX IDX_EXECUTIONS_PARENT_ID
    ON EXECUTIONS(PARENT_EXECUTION_ID);

-- Index global function-based pour PENDING_APPROVAL (V030)
-- (CASE expression sans partition key → global)
CREATE INDEX IDX_EXECUTIONS_PENDING_APPROVAL ON EXECUTIONS(
    CASE WHEN STATUS = 'PENDING_APPROVAL' THEN ID END
);

-- Index supprimés (remplacés / redondants) :
--   IDX_EXECUTIONS_ACTION_ID  (V023 — remplacé par IDX_EXECUTIONS_CREATED_ACTION)
--   IDX_EXECUTIONS_CREATED_AT (V023 — redondant avec partitionnement)
-- Ces index existent sur EXECUTIONS_OLD et sont détruits avec DROP TABLE EXECUTIONS_OLD PURGE

-- ============================================================
-- PHASE 9 : Recréer les contraintes CHECK
-- ============================================================
-- STATUS (version V057 avec INTEGRATION_ERROR)
ALTER TABLE EXECUTIONS ADD CONSTRAINT CHK_EXECUTION_STATUS
    CHECK (STATUS IN (
        'SUBMITTED', 'INTEGRATION_ERROR', 'PENDING_APPROVAL',
        'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REJECTED'
    ));

-- ENVIRONMENT (V023)
ALTER TABLE EXECUTIONS ADD CONSTRAINT CHK_EXECUTION_ENV
    CHECK (ENVIRONMENT IN ('dev', 'staging', 'prod'));

-- ============================================================
-- PHASE 10 : Validation de l'intégrité (COUNT*)
-- ============================================================
DECLARE
    v_old_count NUMBER;
    v_new_count NUMBER;
BEGIN
    SELECT ROW_COUNT INTO v_old_count FROM EXECUTIONS_MIGRATION_CHECK;
    SELECT COUNT(*) INTO v_new_count FROM EXECUTIONS;
    IF v_new_count != v_old_count THEN
        RAISE_APPLICATION_ERROR(-20002,
            'ROW COUNT MISMATCH: expected ' || v_old_count
            || ' but migrated ' || v_new_count || ' rows. MANUAL INTERVENTION REQUIRED.');
    END IF;
    DBMS_OUTPUT.PUT_LINE('V084 migration validated: ' || v_new_count || ' rows migrated successfully.');
END;
/

-- ============================================================
-- PHASE 11 : Nettoyage (seulement après validation Phase 10)
-- ============================================================
DROP TABLE EXECUTIONS_OLD PURGE;
DROP TABLE EXECUTIONS_MIGRATION_CHECK PURGE;

-- ============================================================
-- COMMENTAIRES FINAUX
-- ============================================================
COMMENT ON TABLE EXECUTIONS IS
    'Execution records for actions. Partitioned by CREATED_AT (monthly INTERVAL). Story 40.2.';
COMMENT ON COLUMN EXECUTIONS.CREATED_AT IS
    'UTC TIMESTAMP used as partition key (monthly INTERVAL partitioning). V084.';
COMMENT ON COLUMN EXECUTIONS.ID IS
    'Primary key, IDENTITY column. Backed by global unique index (PK_EXECUTIONS). V084.';
