-- V085: Reference Partition EXECUTION_STEPS via FK to EXECUTIONS
-- Story 40.3 - Epic 40: Partitionnement et rétention tables performance
-- Approche: Reference Partitioning (hérite la structure de partitions de EXECUTIONS)
-- Prérequis: V084 appliqué (EXECUTIONS partitionnée), FK ENABLED
-- Maintenance window estimate: 2-4h (plus rapide que 40.2 : aucune FK entrante vers EXECUTION_STEPS)
-- Rollback: see database/rollback/V085__partition_execution_steps_rollback.sql
--
-- COLONNES (état après V048) :
--   ID (IDENTITY), EXECUTION_ID, STEP_ORDER, STEP_NAME, STEP_TYPE,
--   STATUS (DEFAULT 'PENDING'), STARTED_AT, COMPLETED_AT, OUTPUT (CLOB),
--   PLATFORM_JOB_ID, ERROR_MESSAGE (CLOB), CREATED_AT (TIMESTAMP, V048)
--
-- CONTRAINTES RECRÉÉES :
--   PK_EXECUTION_STEPS (ID) → index GLOBAL
--   FK_EXEC_STEPS_NEW_EXEC (EXECUTION_ID → EXECUTIONS.ID, CASCADE) → inline pour PARTITION BY REFERENCE
--   UK_EXEC_STEPS_EXEC_ORDER (EXECUTION_ID, STEP_ORDER) → LOCAL prefixed
--   CHK_STEP_STATUS (STATUS IN 'PENDING','WAITING','RUNNING','COMPLETED','FAILED','SKIPPED') ← V067
--   CHK_STEP_TYPE  (STEP_TYPE IN 'vault','servicenow','platform','prerequisite','verification') ← V025
--
-- INDEX RECRÉÉS :
--   IDX_EXEC_STEPS_EXECUTION_ID (EXECUTION_ID) → LOCAL
--   IDX_EXEC_STEPS_EXEC_STATUS  (EXECUTION_ID, STATUS) → LOCAL prefixed
--
-- INDEX SUPPRIMÉS (avec DROP TABLE EXECUTION_STEPS_OLD PURGE en Phase 10) :
--   IDX_EXEC_STEPS_STATUS (STATUS seul) → remplacé par IDX_EXEC_STEPS_EXEC_STATUS
--
-- CONTRAINTES SUPPRIMÉES (avec DROP TABLE EXECUTION_STEPS_OLD PURGE) :
--   UQ_EXEC_STEP_ORDER (EXECUTION_ID, STEP_ORDER) → remplacée par UK_EXEC_STEPS_EXEC_ORDER LOCAL

-- ============================================================
-- PHASE 0 : Vérification des préconditions (idempotence)
-- ============================================================
DECLARE
    v_count        NUMBER;
    v_exec_parted  VARCHAR2(3);
    v_fk_status    VARCHAR2(8);
BEGIN
    -- Vérifier EXECUTION_STEPS_NEW absent (idempotence)
    SELECT COUNT(*) INTO v_count
    FROM USER_TABLES WHERE TABLE_NAME = 'EXECUTION_STEPS_NEW';
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'EXECUTION_STEPS_NEW already exists - check previous migration state and clean up manually');
    END IF;

    -- Vérifier EXECUTION_STEPS_OLD absent (idempotence)
    SELECT COUNT(*) INTO v_count
    FROM USER_TABLES WHERE TABLE_NAME = 'EXECUTION_STEPS_OLD';
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20003,
            'EXECUTION_STEPS_OLD already exists - check previous migration state and clean up manually');
    END IF;

    -- Vérifier EXEC_STEPS_MIGRATION_CHECK absente (idempotence — bug 40.2 corrigé)
    SELECT COUNT(*) INTO v_count
    FROM USER_TABLES WHERE TABLE_NAME = 'EXEC_STEPS_MIGRATION_CHECK';
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20004,
            'EXEC_STEPS_MIGRATION_CHECK already exists - Phase 1 ran previously but migration did not complete. Clean up manually: DROP TABLE EXEC_STEPS_MIGRATION_CHECK PURGE');
    END IF;

    -- Vérifier EXECUTIONS est bien partitionnée (prérequis V084)
    SELECT PARTITIONED INTO v_exec_parted
    FROM USER_TABLES WHERE TABLE_NAME = 'EXECUTIONS';
    IF v_exec_parted != 'YES' THEN
        RAISE_APPLICATION_ERROR(-20002,
            'EXECUTIONS is not partitioned - V084 must be applied before V085');
    END IF;

    -- Vérifier la FK EXECUTION_STEPS.EXECUTION_ID → EXECUTIONS est ENABLED
    SELECT STATUS INTO v_fk_status
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'EXECUTION_STEPS'
      AND CONSTRAINT_TYPE = 'R'
      AND R_CONSTRAINT_NAME = (
          SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS
          WHERE TABLE_NAME = 'EXECUTIONS' AND CONSTRAINT_TYPE = 'P'
      )
    AND ROWNUM = 1;
    IF v_fk_status != 'ENABLED' THEN
        RAISE_APPLICATION_ERROR(-20005,
            'FK EXECUTION_STEPS.EXECUTION_ID is not ENABLED - required for Reference Partitioning');
    END IF;
END;
/

-- ============================================================
-- PHASE 1 : Snapshot de contrôle (COUNT avant migration)
-- ============================================================
CREATE TABLE EXEC_STEPS_MIGRATION_CHECK AS
    SELECT COUNT(*) AS ROW_COUNT FROM EXECUTION_STEPS;

-- ============================================================
-- PHASE 2 : Créer la nouvelle table partitionnée (Reference Partitioning)
-- IMPORTANT : La FK doit être déclarée INLINE avec un nom explicite.
--             PARTITION BY REFERENCE référence ce nom de contrainte.
-- ============================================================
CREATE TABLE EXECUTION_STEPS_NEW (
    ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    EXECUTION_ID    NUMBER NOT NULL,
    STEP_ORDER      NUMBER NOT NULL,
    STEP_NAME       VARCHAR2(255) NOT NULL,
    STEP_TYPE       VARCHAR2(50) NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    STARTED_AT      TIMESTAMP,
    COMPLETED_AT    TIMESTAMP,
    OUTPUT          CLOB,
    PLATFORM_JOB_ID VARCHAR2(255),
    ERROR_MESSAGE   CLOB,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_EXECUTION_STEPS_NEW PRIMARY KEY (ID),
    CONSTRAINT FK_EXEC_STEPS_NEW_EXEC
        FOREIGN KEY (EXECUTION_ID) REFERENCES EXECUTIONS(ID) ON DELETE CASCADE ENABLE
)
PARTITION BY REFERENCE (FK_EXEC_STEPS_NEW_EXEC);

-- ============================================================
-- PHASE 3 : Migration des données
-- ============================================================
INSERT /*+ APPEND PARALLEL(4) */ INTO EXECUTION_STEPS_NEW
    (ID, EXECUTION_ID, STEP_ORDER, STEP_NAME, STEP_TYPE, STATUS,
     STARTED_AT, COMPLETED_AT, OUTPUT, PLATFORM_JOB_ID, ERROR_MESSAGE, CREATED_AT)
SELECT
     ID, EXECUTION_ID, STEP_ORDER, STEP_NAME, STEP_TYPE, STATUS,
     STARTED_AT, COMPLETED_AT, OUTPUT, PLATFORM_JOB_ID, ERROR_MESSAGE, CREATED_AT
FROM EXECUTION_STEPS;
COMMIT;

-- ============================================================
-- PHASE 4 : Renommage
-- ============================================================
ALTER TABLE EXECUTION_STEPS RENAME TO EXECUTION_STEPS_OLD;
ALTER TABLE EXECUTION_STEPS_NEW RENAME TO EXECUTION_STEPS;
ALTER TABLE EXECUTION_STEPS RENAME CONSTRAINT PK_EXECUTION_STEPS_NEW TO PK_EXECUTION_STEPS;

-- ============================================================
-- PHASE 5 : Recréer le UK local prefixed (EXECUTION_ID = clé de référence héritée)
-- Un index local UNIQUE sur (EXECUTION_ID, STEP_ORDER) est globalement unique
-- car chaque EXECUTION_ID appartient à exactement une partition.
-- ============================================================
ALTER TABLE EXECUTION_STEPS ADD CONSTRAINT UK_EXEC_STEPS_EXEC_ORDER
    UNIQUE (EXECUTION_ID, STEP_ORDER)
    USING INDEX LOCAL;

-- ============================================================
-- PHASE 6 : Recréer les CHECK constraints (STATUS + STEP_TYPE)
-- Valeurs issues de V025 (STEP_TYPE) et V025 + V067 (STATUS avec WAITING)
-- ============================================================
-- STATUS (V025 + V067 : ajout WAITING)
ALTER TABLE EXECUTION_STEPS ADD CONSTRAINT CHK_STEP_STATUS
    CHECK (STATUS IN ('PENDING', 'WAITING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED'));

-- STEP_TYPE (V025 — valeurs vérifiées dans USER_CONSTRAINTS + code source)
ALTER TABLE EXECUTION_STEPS ADD CONSTRAINT CHK_STEP_TYPE
    CHECK (STEP_TYPE IN ('vault', 'servicenow', 'platform', 'prerequisite', 'verification'));

-- ============================================================
-- PHASE 7 : Recréer les index locaux
-- ============================================================
-- Index local sur EXECUTION_ID (partition key de référence héritée)
CREATE INDEX IDX_EXEC_STEPS_EXECUTION_ID ON EXECUTION_STEPS(EXECUTION_ID) LOCAL;

-- Index local prefixed (EXECUTION_ID, STATUS) pour partition pruning sur requêtes STATUS
-- Remplace IDX_EXEC_STEPS_STATUS (STATUS seul) — supprimé avec EXECUTION_STEPS_OLD en Phase 10
CREATE INDEX IDX_EXEC_STEPS_EXEC_STATUS ON EXECUTION_STEPS(EXECUTION_ID, STATUS) LOCAL;

-- ============================================================
-- PHASE 8 : Recalibrer la séquence IDENTITY (même pattern que V084)
-- ============================================================
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(ID), 0) INTO v_max FROM EXECUTION_STEPS;
    IF v_max > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE EXECUTION_STEPS MODIFY ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH '
            || (v_max + 1) || ' INCREMENT BY 1 NOCACHE)';
    END IF;
END;
/

-- ============================================================
-- PHASE 9 : Valider l'intégrité (COUNT*)
-- ============================================================
DECLARE
    v_old_count NUMBER;
    v_new_count NUMBER;
BEGIN
    SELECT ROW_COUNT INTO v_old_count FROM EXEC_STEPS_MIGRATION_CHECK;
    SELECT COUNT(*) INTO v_new_count FROM EXECUTION_STEPS;
    IF v_new_count != v_old_count THEN
        RAISE_APPLICATION_ERROR(-20006,
            'ROW COUNT MISMATCH: expected ' || v_old_count
            || ' but migrated ' || v_new_count || ' rows. MANUAL INTERVENTION REQUIRED.');
    END IF;
    DBMS_OUTPUT.PUT_LINE('V085 migration validated: ' || v_new_count || ' rows migrated successfully.');
END;
/

-- ============================================================
-- PHASE 10 : Nettoyage (seulement après validation Phase 9)
-- ============================================================
DROP TABLE EXECUTION_STEPS_OLD PURGE;
DROP TABLE EXEC_STEPS_MIGRATION_CHECK PURGE;

-- ============================================================
-- COMMENTAIRES FINAUX
-- ============================================================
COMMENT ON TABLE EXECUTION_STEPS IS
    'Execution step records. Reference Partitioned by FK EXECUTION_ID → EXECUTIONS (monthly INTERVAL). Story 40.3.';
COMMENT ON COLUMN EXECUTION_STEPS.EXECUTION_ID IS
    'FK to EXECUTIONS.ID — partition key héritée (Reference Partitioning). V085.';
COMMENT ON COLUMN EXECUTION_STEPS.ID IS
    'Primary key, IDENTITY column. Backed by global unique index (PK_EXECUTION_STEPS). V085.';
