-- V086: Partition AUDIT_LOG by TIMESTAMP (Range INTERVAL monthly)
-- Story 40.4 - Epic 40: Partitionnement et rétention tables performance
-- Approche: Range INTERVAL Partitioning sur TIMESTAMP (clé de partition naturelle)
-- Prérequis: Aucun (AUDIT_LOG est indépendante d'EXECUTIONS/EXECUTION_STEPS)
-- Maintenance window estimate: 4-6h
-- Rollback: see database/rollback/V086__partition_audit_log_rollback.sql
--
-- COLONNES (état après V028) :
--   ID (GENERATED ALWAYS AS IDENTITY → migré en BY DEFAULT ON NULL), TIMESTAMP,
--   USER_ID, ACTION_TYPE, ENTITY_TYPE, ENTITY_ID, DETAILS (CLOB),
--   IP_ADDRESS, CORRELATION_ID
--
-- PARTICULARITÉ CRITIQUE :
--   AUDIT_LOG utilise GENERATED ALWAYS AS IDENTITY (V004), contrairement à
--   EXECUTIONS/EXECUTION_STEPS qui utilisent GENERATED BY DEFAULT ON NULL.
--   → AUDIT_LOG_NEW DOIT utiliser GENERATED BY DEFAULT ON NULL AS IDENTITY
--     pour permettre INSERT avec ID explicite lors de la copie (sinon ORA-32795).
--
-- CONTRAINTES RECRÉÉES :
--   PK_AUDIT_LOG (ID) → index GLOBAL (unicité inter-partitions)
--   CK_AUDIT_LOG_ACTION_TYPE → valeurs V068 (toutes les valeurs courantes)
--   CK_AUDIT_LOG_ENTITY_TYPE → valeurs V045
--
-- INDEX RECRÉÉS :
--   IDX_AUDIT_LOG_TIMESTAMP (TIMESTAMP) → LOCAL prefixed (clé de partition)
--   IDX_AUDITLOG_CREATED_ENTITY (TIMESTAMP, ENTITY_TYPE, ENTITY_ID) → LOCAL prefixed
--   IDX_AUDITLOG_CREATED_USER (TIMESTAMP, USER_ID) → LOCAL prefixed
--   IDX_AUDIT_LOG_CREATED_ACTION (TIMESTAMP, ACTION_TYPE) → LOCAL prefixed
--   IDX_AUDIT_LOG_CORRELATION (CORRELATION_ID) → GLOBAL (requêtes sans filtre date)
--
-- INDEX SUPPRIMÉS (avec DROP TABLE AUDIT_LOG_OLD PURGE en Phase 12) :
--   IDX_AUDIT_LOG_TIMESTAMP (ancien, non-partitionné) → remplacé par version LOCAL
--   IDX_AUDIT_LOG_ENTITY (ENTITY_TYPE, ENTITY_ID) → remplacé par IDX_AUDITLOG_CREATED_ENTITY
--   IDX_AUDIT_LOG_USER (USER_ID) → remplacé par IDX_AUDITLOG_CREATED_USER
--   IDX_AUDIT_LOG_ACTION_TYPE (ACTION_TYPE) → remplacé par IDX_AUDIT_LOG_CREATED_ACTION
--   IDX_AUDIT_LOG_ENTITY_TYPE_TIMESTAMP (V029) → remplacé par IDX_AUDITLOG_CREATED_ENTITY
--
-- TRIGGER RECRÉÉ :
--   TRG_AUDIT_LOG_IMMUTABLE (BEFORE UPDATE OR DELETE) → SOC1/NFR8 compliance
--   CRITIQUE: Le trigger reste attaché à AUDIT_LOG_OLD après renommage —
--             doit être explicitement recréé sur la nouvelle table AUDIT_LOG.

-- ============================================================
-- PHASE 0 : Vérification des préconditions (idempotence)
-- ============================================================
DECLARE
    v_new_exists     NUMBER;
    v_check_exists   NUMBER;
    v_old_exists     NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_new_exists
    FROM USER_TABLES WHERE TABLE_NAME = 'AUDIT_LOG_NEW';
    IF v_new_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'AUDIT_LOG_NEW already exists - check previous migration state and clean up manually');
    END IF;

    SELECT COUNT(*) INTO v_check_exists
    FROM USER_TABLES WHERE TABLE_NAME = 'AUDIT_LOG_MIGRATION_CHECK';
    IF v_check_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20002,
            'AUDIT_LOG_MIGRATION_CHECK already exists - Phase 1 ran previously but migration did not complete. Clean up manually: DROP TABLE AUDIT_LOG_MIGRATION_CHECK PURGE');
    END IF;

    SELECT COUNT(*) INTO v_old_exists
    FROM USER_TABLES WHERE TABLE_NAME = 'AUDIT_LOG_OLD';
    IF v_old_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20003,
            'AUDIT_LOG_OLD already exists - check previous migration state and clean up manually');
    END IF;
END;
/

-- ============================================================
-- PHASE 1 : Snapshot de contrôle (COUNT avant migration)
-- ============================================================
CREATE TABLE AUDIT_LOG_MIGRATION_CHECK AS
    SELECT COUNT(*) AS ROW_COUNT FROM AUDIT_LOG;

-- ============================================================
-- PHASE 2 : Créer AUDIT_LOG_NEW partitionnée (Range INTERVAL mensuel)
-- NOTE : GENERATED BY DEFAULT ON NULL (pas GENERATED ALWAYS) pour permettre
--        INSERT avec ID explicite lors de la copie. Sinon ORA-32795.
--        La séquence sera recalibrée en Phase 8 après la copie.
-- ============================================================
CREATE TABLE AUDIT_LOG_NEW (
    ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    TIMESTAMP       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    USER_ID         VARCHAR2(100) NOT NULL,
    ACTION_TYPE     VARCHAR2(50) NOT NULL,
    ENTITY_TYPE     VARCHAR2(50) NOT NULL,
    ENTITY_ID       NUMBER NOT NULL,
    DETAILS         CLOB,
    IP_ADDRESS      VARCHAR2(45),
    CORRELATION_ID  VARCHAR2(64),
    CONSTRAINT PK_AUDIT_LOG_NEW PRIMARY KEY (ID)
)
PARTITION BY RANGE (TIMESTAMP)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_INITIAL VALUES LESS THAN (TIMESTAMP '2020-01-01 00:00:00')
);

-- ============================================================
-- PHASE 3 : Migration des données
-- ============================================================
INSERT /*+ APPEND PARALLEL(4) */ INTO AUDIT_LOG_NEW
    (ID, TIMESTAMP, USER_ID, ACTION_TYPE, ENTITY_TYPE, ENTITY_ID,
     DETAILS, IP_ADDRESS, CORRELATION_ID)
SELECT
     ID, TIMESTAMP, USER_ID, ACTION_TYPE, ENTITY_TYPE, ENTITY_ID,
     DETAILS, IP_ADDRESS, CORRELATION_ID
FROM AUDIT_LOG;
COMMIT;

-- ============================================================
-- PHASE 4 : Renommage
-- ============================================================
ALTER TABLE AUDIT_LOG RENAME TO AUDIT_LOG_OLD;
ALTER TABLE AUDIT_LOG_NEW RENAME TO AUDIT_LOG;
ALTER TABLE AUDIT_LOG RENAME CONSTRAINT PK_AUDIT_LOG_NEW TO PK_AUDIT_LOG;

-- ============================================================
-- PHASE 5 : Recréer les CHECK constraints (valeurs V068/V045)
-- IMPORTANT : Ces valeurs correspondent à l'état après V068 (ACTION_TYPE)
--             et V045 (ENTITY_TYPE). Vérifier les valeurs exactes si des
--             migrations ont été appliquées après V068 :
--             SELECT CONSTRAINT_NAME, SEARCH_CONDITION
--             FROM USER_CONSTRAINTS WHERE TABLE_NAME='AUDIT_LOG_OLD' AND CONSTRAINT_TYPE='C';
-- ============================================================
ALTER TABLE AUDIT_LOG ADD CONSTRAINT CK_AUDIT_LOG_ACTION_TYPE CHECK (
    ACTION_TYPE IN (
        -- Action lifecycle
        'ACTION_CREATED', 'ACTION_UPDATED', 'ACTION_PUBLISHED',
        'ACTION_DISABLED', 'ACTION_ENABLED', 'ACTION_DELETED',
        'ACTION_DEACTIVATED', 'ACTION_REACTIVATED',
        -- Profile lifecycle
        'PROFILE_CREATED', 'PROFILE_UPDATED', 'PROFILE_DELETED', 'PROFILE_UPDATE_REJECTED',
        -- Integration lifecycle
        'INTEGRATION_CREATED', 'INTEGRATION_UPDATED', 'INTEGRATION_DELETED',
        'INTEGRATION_TYPE_CREATED', 'INTEGRATION_TYPE_UPDATED',
        'INTEGRATION_ACTION_CREATED', 'INTEGRATION_ACTION_UPDATED',
        'INTEGRATION_STATUS_UPDATED', 'INTEGRATION_MARKED_LEGACY',
        -- Execution lifecycle
        'EXECUTION_SUBMITTED', 'EXECUTION_STARTED', 'EXECUTION_RUNNING',
        'EXECUTION_COMPLETED', 'EXECUTION_FAILED', 'EXECUTION_CANCELLED',
        'EXECUTION_PENDING_APPROVAL', 'EXECUTION_APPROVED', 'EXECUTION_REJECTED',
        'EXECUTION_TARGET_FORBIDDEN', 'EXECUTION_INTEGRATION_ERROR',
        'EXECUTION_BLOCKED_INVALID_INTEGRATION', 'EXECUTION_DEPRECATED_INTEGRATION_WARNING',
        'WORKFLOW_STEP_BLOCKED_INVALID_INTEGRATION',
        -- ServiceNow
        'SERVICENOW_CHANGE_CREATED',
        -- Remediation
        'REMEDIATION_EXECUTION_CREATED',
        'AUTO_REMEDIATION_TRIGGERED', 'AUTO_REMEDIATION_SUCCESS', 'AUTO_REMEDIATION_FAILED',
        -- Scheduled executions
        'SCHEDULED_EXECUTION_CREATED', 'SCHEDULED_EXECUTION_RECURRING_CREATED',
        'SCHEDULED_EXECUTION_EXECUTED', 'SCHEDULED_EXECUTION_CANCELLED',
        'SCHEDULED_EXECUTION_RECURRING_DISABLED',
        -- User / Auth / Favorites
        'USER_CREATED', 'USER_UPDATED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_REFRESH',
        'FAVORITE_ADDED', 'FAVORITE_REMOVED',
        -- Execution step retry
        'EXECUTION_STEP_RETRY_ATTEMPT', 'EXECUTION_STEP_RETRY_SUCCESS',
        'EXECUTION_STEP_RETRY_EXHAUSTED', 'EXECUTION_STEP_RETRY_ABORTED',
        -- Feature flags
        'FEATURE_FLAG_CREATED', 'FEATURE_FLAG_UPDATED'
    )
);

ALTER TABLE AUDIT_LOG ADD CONSTRAINT CK_AUDIT_LOG_ENTITY_TYPE CHECK (
    ENTITY_TYPE IN (
        'action', 'user', 'permission', 'execution',
        'scheduled_execution', 'integration', 'profile'
    )
);

-- ============================================================
-- PHASE 6 : Recréer les index locaux prefixed
-- (Le mot-clé LOCAL crée un index sub-partitionné par partition)
-- ============================================================
-- Index local sur TIMESTAMP (clé de partition) — remplace l'ancien IDX_AUDIT_LOG_TIMESTAMP non-partitionné
CREATE INDEX IDX_AUDIT_LOG_TIMESTAMP ON AUDIT_LOG(TIMESTAMP) LOCAL;

-- Index local prefixed (TIMESTAMP, ENTITY_TYPE, ENTITY_ID)
-- Remplace IDX_AUDIT_LOG_ENTITY + IDX_AUDIT_LOG_ENTITY_TYPE_TIMESTAMP (V029)
CREATE INDEX IDX_AUDITLOG_CREATED_ENTITY ON AUDIT_LOG(TIMESTAMP, ENTITY_TYPE, ENTITY_ID) LOCAL;

-- Index local prefixed (TIMESTAMP, USER_ID) — remplace IDX_AUDIT_LOG_USER
CREATE INDEX IDX_AUDITLOG_CREATED_USER ON AUDIT_LOG(TIMESTAMP, USER_ID) LOCAL;

-- Index local prefixed (TIMESTAMP, ACTION_TYPE) — remplace IDX_AUDIT_LOG_ACTION_TYPE
CREATE INDEX IDX_AUDIT_LOG_CREATED_ACTION ON AUDIT_LOG(TIMESTAMP, ACTION_TYPE) LOCAL;

-- ============================================================
-- PHASE 7 : Index GLOBAL sur CORRELATION_ID (requêtes sans filtre date)
-- GLOBAL car les requêtes par CORRELATION_ID n'ont pas de filtre TIMESTAMP
-- ============================================================
CREATE INDEX IDX_AUDIT_LOG_CORRELATION ON AUDIT_LOG(CORRELATION_ID);

-- ============================================================
-- PHASE 8 : Recalibrer la séquence IDENTITY (START WITH MAX(ID)+1)
-- Nécessaire car AUDIT_LOG_NEW a une séquence qui repart de 1.
-- Sans cette phase, les prochains INSERTs auront des conflits de PK.
-- ============================================================
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(ID), 0) INTO v_max FROM AUDIT_LOG;
    IF v_max > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE AUDIT_LOG MODIFY ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH '
            || (v_max + 1) || ' INCREMENT BY 1 NOCACHE)';
    END IF;
END;
/

-- ============================================================
-- PHASE 9 : Recréer le trigger d'immutabilité (SOC1/NFR8)
-- CRITIQUE : TRG_AUDIT_LOG_IMMUTABLE (V054) reste attaché à AUDIT_LOG_OLD après renommage.
--            La nouvelle table AUDIT_LOG n'a AUCUN trigger après Phase 4.
--            Cette phase est OBLIGATOIRE pour maintenir la compliance SOC1/NFR8.
-- ============================================================
CREATE OR REPLACE TRIGGER TRG_AUDIT_LOG_IMMUTABLE
BEFORE UPDATE OR DELETE ON AUDIT_LOG
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001,
        'AUDIT_LOG is immutable - UPDATE and DELETE operations are forbidden (SOC1/NFR8)');
END;
/

-- ============================================================
-- PHASE 10 : Valider l'intégrité (COUNT*)
-- ============================================================
DECLARE
    v_old_count NUMBER;
    v_new_count NUMBER;
BEGIN
    SELECT ROW_COUNT INTO v_old_count FROM AUDIT_LOG_MIGRATION_CHECK;
    SELECT COUNT(*) INTO v_new_count FROM AUDIT_LOG;
    IF v_new_count != v_old_count THEN
        RAISE_APPLICATION_ERROR(-20004,
            'ROW COUNT MISMATCH: expected ' || v_old_count
            || ' but migrated ' || v_new_count || ' rows. MANUAL INTERVENTION REQUIRED.');
    END IF;
    DBMS_OUTPUT.PUT_LINE('V086 migration validated: ' || v_new_count || ' rows migrated successfully.');
END;
/

-- ============================================================
-- PHASE 11 : Nettoyage (seulement après validation Phase 10)
-- DROP TABLE AUDIT_LOG_OLD PURGE supprime également automatiquement :
--   - L'ancien TRG_AUDIT_LOG_IMMUTABLE (attaché à AUDIT_LOG_OLD)
--   - Tous les anciens index non-partitionnés de la table originale
--   - IDX_AUDIT_LOG_ENTITY_TYPE_TIMESTAMP (V029) — remplacé par IDX_AUDITLOG_CREATED_ENTITY
-- ============================================================
DROP TABLE AUDIT_LOG_OLD PURGE;
DROP TABLE AUDIT_LOG_MIGRATION_CHECK PURGE;

-- ============================================================
-- COMMENTAIRES FINAUX
-- ============================================================
COMMENT ON TABLE AUDIT_LOG IS
    'Append-only audit log. Range INTERVAL Partitioned by TIMESTAMP (monthly). Story 40.4. SOC1/NFR8: immutable via trigger TRG_AUDIT_LOG_IMMUTABLE.';
COMMENT ON COLUMN AUDIT_LOG.TIMESTAMP IS
    'Partition key (Range INTERVAL monthly). Auto-set to SYSTIMESTAMP on INSERT. V086.';
COMMENT ON COLUMN AUDIT_LOG.ID IS
    'Primary key, IDENTITY column (BY DEFAULT ON NULL after V086 migration). Backed by global unique index PK_AUDIT_LOG.';
COMMENT ON COLUMN AUDIT_LOG.CORRELATION_ID IS
    'Optional correlation ID for cross-request tracing. Indexed via IDX_AUDIT_LOG_CORRELATION (GLOBAL) for queries without date filter.';
