-- V087: Procédure de purge et politique de rétention — PKG_IDP_MAINTENANCE
-- Story 40.5 - Epic 40: Partitionnement et rétention tables performance
-- Installe : TABLE IDP_MAINTENANCE_LOG + PACKAGE PKG_IDP_MAINTENANCE
-- Rollback: see database/rollback/V087__create_purge_procedure_rollback.sql
--
-- TABLES CIBLES :
--   EXECUTIONS          — partitionnée CREATED_AT Range INTERVAL (V084), rétention 24 mois
--   EXECUTION_STEPS     — Reference Partitioning sur FK EXECUTION_ID→EXECUTIONS (V085)
--                         → partitions cascadent automatiquement avec EXECUTIONS
--   AUDIT_LOG           — partitionnée TIMESTAMP Range INTERVAL (V086), rétention 12 mois
--                         ⚠️ SOC1/NFR8 : purge AUDIT_LOG désactivée par défaut (p_dry_run=1)
--
-- ORDRE DE PURGE (EXECUTIONS) :
--   1. UPDATE EXECUTIONS SET PARENT_EXECUTION_ID = NULL WHERE ... (pré-requis FK auto-ref)
--   2. DELETE FROM EXECUTION_TARGETS WHERE ... (pré-requis FK classique)
--   3. ALTER TABLE EXECUTIONS DROP PARTITION p_name UPDATE GLOBAL INDEXES
--      → EXECUTION_STEPS cascade automatiquement (Reference Partitioning)
--
-- DÉPENDANCES :
--   - EXECUTIONS partitionnée (V084) — colonne CREATED_AT comme clé de partition
--   - EXECUTION_STEPS Reference Partitioned (V085) — cascade automatique
--   - AUDIT_LOG partitionnée (V086) — colonne TIMESTAMP comme clé de partition
--   - EXECUTION_TARGETS non-partitionné — FK EXECUTION_ID → EXECUTIONS.ID (classique)
--   - FK_EXECUTIONS_PARENT : DEFERRABLE INITIALLY DEFERRED (V084 Phase 6)

-- ============================================================
-- PHASE 0 : Vérification des préconditions (idempotence)
-- ============================================================
-- Ce script est idempotent : il peut être re-exécuté sans erreur.
-- - Si les deux objets existent déjà → installation complète détectée, message et poursuite.
-- - Si un seul des deux existe → installation partielle → erreur explicite pour guide DBA.
-- - Si aucun n'existe → installation fraîche.
DECLARE
    v_pkg_exists   NUMBER;
    v_table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_pkg_exists
    FROM USER_OBJECTS
    WHERE OBJECT_NAME = 'PKG_IDP_MAINTENANCE'
      AND OBJECT_TYPE IN ('PACKAGE', 'PACKAGE BODY');

    SELECT COUNT(*) INTO v_table_exists
    FROM USER_TABLES
    WHERE TABLE_NAME = 'IDP_MAINTENANCE_LOG';

    IF v_pkg_exists > 0 AND v_table_exists > 0 THEN
        DBMS_OUTPUT.PUT_LINE(
            'V087: PKG_IDP_MAINTENANCE and IDP_MAINTENANCE_LOG already exist — '
            || 'running in idempotent mode (CREATE OR REPLACE for package, skip for table).');
    ELSIF v_pkg_exists > 0 AND v_table_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'V087 partial installation: PKG_IDP_MAINTENANCE exists but IDP_MAINTENANCE_LOG is missing. '
            || 'Clean up manually: DROP PACKAGE PKG_IDP_MAINTENANCE');
    ELSIF v_pkg_exists = 0 AND v_table_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20002,
            'V087 partial installation: IDP_MAINTENANCE_LOG exists but PKG_IDP_MAINTENANCE is missing. '
            || 'Clean up manually: DROP TABLE IDP_MAINTENANCE_LOG PURGE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('V087 preconditions OK — clean installation starting.');
    END IF;
END;
/

-- ============================================================
-- PHASE 1 : Créer la table de log de maintenance IDP_MAINTENANCE_LOG
-- (idempotente : ignorée si la table existe déjà)
-- ============================================================
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'IDP_MAINTENANCE_LOG';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE IDP_MAINTENANCE_LOG (
                ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT PK_IDP_MAINTENANCE_LOG PRIMARY KEY,
                EXECUTED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                TABLE_NAME     VARCHAR2(64)  NOT NULL,
                PARTITION_NAME VARCHAR2(64)  NOT NULL,
                ACTION         VARCHAR2(32)  NOT NULL,
                STATUS         VARCHAR2(16)  NOT NULL,
                DRY_RUN        NUMBER(1)     DEFAULT 1 NOT NULL,
                NOTES          VARCHAR2(500)
            )';
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_MAINT_LOG_EXECUTED_AT ON IDP_MAINTENANCE_LOG(EXECUTED_AT)';
        DBMS_OUTPUT.PUT_LINE('IDP_MAINTENANCE_LOG and IDX_MAINT_LOG_EXECUTED_AT created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('IDP_MAINTENANCE_LOG already exists — skipping creation (idempotent).');
    END IF;
END;
/

COMMENT ON TABLE IDP_MAINTENANCE_LOG IS
    'Log des opérations de maintenance (purge partitions). Story 40.5. Créée par V087.';
COMMENT ON COLUMN IDP_MAINTENANCE_LOG.ID IS
    'PK IDENTITY.';
COMMENT ON COLUMN IDP_MAINTENANCE_LOG.EXECUTED_AT IS
    'Date/heure de l''opération. Indexée pour monitoring.';
COMMENT ON COLUMN IDP_MAINTENANCE_LOG.TABLE_NAME IS
    'Nom de la table cible (EXECUTIONS, AUDIT_LOG, etc.).';
COMMENT ON COLUMN IDP_MAINTENANCE_LOG.PARTITION_NAME IS
    'Nom Oracle de la partition traitée.';
COMMENT ON COLUMN IDP_MAINTENANCE_LOG.ACTION IS
    'Type d''opération : DROP, SKIP (partition dans fenêtre rétention), PREREQ_UPDATE, PREREQ_DELETE.';
COMMENT ON COLUMN IDP_MAINTENANCE_LOG.STATUS IS
    'Résultat : SUCCESS, DRY_RUN, ERROR.';
COMMENT ON COLUMN IDP_MAINTENANCE_LOG.DRY_RUN IS
    '1 = mode simulation (aucun DROP réel), 0 = exécution effective.';
COMMENT ON COLUMN IDP_MAINTENANCE_LOG.NOTES IS
    'Informations complémentaires (messages d''erreur, estimations de lignes, etc.).';

-- ============================================================
-- PHASE 2 : Créer la spécification du package PKG_IDP_MAINTENANCE
-- ============================================================
CREATE OR REPLACE PACKAGE PKG_IDP_MAINTENANCE AS

    -- ===========================================================
    -- Politique de rétention par défaut (en mois)
    -- Modifiable via les paramètres des procédures publiques.
    -- ===========================================================
    gc_retention_executions  CONSTANT NUMBER := 24;  -- EXECUTIONS : 24 mois
    gc_retention_audit_log   CONSTANT NUMBER := 12;  -- AUDIT_LOG  : 12 mois (SOC1/NFR8)

    -- ===========================================================
    -- Procédure principale : purge toutes les tables configurées
    -- ===========================================================
    -- p_retention_executions : Rétention EXECUTIONS en mois (défaut 24)
    -- p_retention_audit_log  : Rétention AUDIT_LOG en mois (défaut 12)
    -- p_dry_run              : 1 = simulation (log sans DROP), 0 = exécution réelle
    --                          DÉFAUT = 1 pour éviter toute purge accidentelle
    -- ⚠️  AUDIT_LOG : valider conformité SOC1/NFR8 avant d'activer p_dry_run=0
    PROCEDURE purge_old_partitions(
        p_retention_executions  IN NUMBER  DEFAULT 24,
        p_retention_audit_log   IN NUMBER  DEFAULT 12,
        p_dry_run               IN NUMBER  DEFAULT 1
    );

    -- ===========================================================
    -- Procédure ciblée : purge EXECUTIONS uniquement
    -- ===========================================================
    PROCEDURE purge_executions(
        p_retention_months  IN NUMBER  DEFAULT 24,
        p_dry_run           IN NUMBER  DEFAULT 1
    );

    -- ===========================================================
    -- Procédure ciblée : purge AUDIT_LOG uniquement
    -- ===========================================================
    -- ⚠️  Désactivée par défaut (p_dry_run=1) — conformité SOC1/NFR8
    PROCEDURE purge_audit_log(
        p_retention_months  IN NUMBER  DEFAULT 12,
        p_dry_run           IN NUMBER  DEFAULT 1
    );

END PKG_IDP_MAINTENANCE;
/

-- ============================================================
-- PHASE 3 : Créer le corps du package PKG_IDP_MAINTENANCE
-- ============================================================
CREATE OR REPLACE PACKAGE BODY PKG_IDP_MAINTENANCE AS

    -- ===========================================================
    -- Procédure privée : log une opération de maintenance
    -- ===========================================================
    PROCEDURE log_maintenance(
        p_table_name     IN VARCHAR2,
        p_partition_name IN VARCHAR2,
        p_action         IN VARCHAR2,
        p_status         IN VARCHAR2,
        p_dry_run        IN NUMBER,
        p_notes          IN VARCHAR2 DEFAULT NULL
    ) IS
    BEGIN
        INSERT INTO IDP_MAINTENANCE_LOG
            (TABLE_NAME, PARTITION_NAME, ACTION, STATUS, DRY_RUN, NOTES)
        VALUES
            (p_table_name, p_partition_name, p_action, p_status, p_dry_run, p_notes);
        -- COMMIT intentionnellement omis ici : chaque procédure appelante gère ses COMMITs
        -- afin de garantir l'atomicité des opérations pré-DROP.
    EXCEPTION
        WHEN OTHERS THEN
            -- Le log ne doit jamais bloquer l'opération principale.
            -- On utilise DBMS_OUTPUT pour visibilité sans propager l'erreur.
            DBMS_OUTPUT.PUT_LINE(
                'WARNING: IDP_MAINTENANCE_LOG insert failed for '
                || p_table_name || '/' || p_partition_name
                || ' — ' || SQLERRM
            );
    END log_maintenance;

    -- ===========================================================
    -- Procédure interne : convertit HIGH_VALUE en DATE
    -- Oracle stocke HIGH_VALUE comme chaîne dans USER_TAB_PARTITIONS.
    -- Ex : "TIMESTAMP' 2024-01-01 00:00:00'"
    -- Approche : EXECUTE IMMEDIATE 'SELECT <HIGH_VALUE> FROM DUAL'
    -- ===========================================================
    FUNCTION get_partition_date(p_high_value IN VARCHAR2) RETURN DATE IS
        v_date DATE;
    BEGIN
        EXECUTE IMMEDIATE 'SELECT ' || p_high_value || ' FROM DUAL' INTO v_date;
        RETURN v_date;
    EXCEPTION
        WHEN OTHERS THEN
            -- HIGH_VALUE non convertible (MAXVALUE, DEFAULT, etc.) → retourner NULL = ne pas purger.
            -- DBMS_OUTPUT pour distinguer les cas attendus (MAXVALUE) des erreurs inattendues.
            DBMS_OUTPUT.PUT_LINE(
                'get_partition_date: HIGH_VALUE non convertible — SQLERRM=' || SQLERRM
                || ' | HIGH_VALUE=' || SUBSTR(p_high_value, 1, 80)
            );
            RETURN NULL;
    END get_partition_date;

    -- ===========================================================
    -- Implémentation : purge_executions
    -- ===========================================================
    PROCEDURE purge_executions(
        p_retention_months  IN NUMBER  DEFAULT 24,
        p_dry_run           IN NUMBER  DEFAULT 1
    ) IS
        v_cutoff_date   DATE;
        v_part_date     DATE;
        v_rows_estimate NUMBER;
    BEGIN
        -- Date limite : toute partition dont HIGH_VALUE <= v_cutoff_date est hors rétention
        v_cutoff_date := ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -p_retention_months);

        DBMS_OUTPUT.PUT_LINE(
            'purge_executions — cutoff: ' || TO_CHAR(v_cutoff_date, 'YYYY-MM-DD')
            || ' | dry_run: ' || p_dry_run
        );

        FOR r IN (
            SELECT PARTITION_NAME, HIGH_VALUE
            FROM   USER_TAB_PARTITIONS
            WHERE  TABLE_NAME = 'EXECUTIONS'
            AND    PARTITION_NAME != 'P_BEFORE_2024'  -- partition initiale de migration V084 à exclure
            ORDER BY PARTITION_POSITION
        ) LOOP
            v_part_date := get_partition_date(r.HIGH_VALUE);

            IF v_part_date IS NULL THEN
                -- HIGH_VALUE non convertible (ex: MAXVALUE) → ignorer
                DBMS_OUTPUT.PUT_LINE(
                    'SKIP ' || r.PARTITION_NAME || ' — HIGH_VALUE non convertible en date'
                );
                log_maintenance('EXECUTIONS', r.PARTITION_NAME, 'SKIP', 'SKIPPED',
                    p_dry_run, 'HIGH_VALUE non convertible: ' || SUBSTR(r.HIGH_VALUE, 1, 100));
                CONTINUE;
            END IF;

            IF v_part_date <= v_cutoff_date THEN
                -- Partition hors fenêtre de rétention → à purger

                DBMS_OUTPUT.PUT_LINE(
                    (CASE WHEN p_dry_run = 1 THEN '[DRY_RUN] ' ELSE '[EXECUTE] ' END)
                    || 'DROP PARTITION EXECUTIONS.' || r.PARTITION_NAME
                    || ' (HIGH_VALUE=' || TO_CHAR(v_part_date, 'YYYY-MM-DD') || ')'
                );

                IF p_dry_run = 0 THEN
                    -- ---------------------------------------------------------
                    -- Pré-requis 1 : Nullifier PARENT_EXECUTION_ID auto-référencé
                    -- Obligatoire avant DROP PARTITION : les executions récentes
                    -- pourraient pointer vers des executions de cette partition.
                    -- FK_EXECUTIONS_PARENT est DEFERRABLE INITIALLY DEFERRED (V084).
                    -- ---------------------------------------------------------
                    EXECUTE IMMEDIATE
                        'UPDATE EXECUTIONS SET PARENT_EXECUTION_ID = NULL '
                        || 'WHERE PARENT_EXECUTION_ID IN '
                        || '(SELECT ID FROM EXECUTIONS PARTITION (' || r.PARTITION_NAME || '))';

                    log_maintenance('EXECUTIONS', r.PARTITION_NAME, 'PREREQ_UPDATE',
                        'SUCCESS', 0,
                        'PARENT_EXECUTION_ID nullified: ' || SQL%ROWCOUNT || ' rows');

                    -- ---------------------------------------------------------
                    -- Pré-requis 2 : Supprimer les lignes orphelines dans EXECUTION_TARGETS
                    -- EXECUTION_TARGETS n'est pas partitionné (FK classique → EXECUTIONS.ID).
                    -- Les lignes référençant cette partition seraient orphelines après DROP.
                    -- ---------------------------------------------------------
                    EXECUTE IMMEDIATE
                        'DELETE FROM EXECUTION_TARGETS '
                        || 'WHERE EXECUTION_ID IN '
                        || '(SELECT ID FROM EXECUTIONS PARTITION (' || r.PARTITION_NAME || '))';

                    log_maintenance('EXECUTIONS', r.PARTITION_NAME, 'PREREQ_DELETE',
                        'SUCCESS', 0,
                        'EXECUTION_TARGETS orphelins supprimés: ' || SQL%ROWCOUNT || ' rows');

                    COMMIT;  -- Commit des pré-requis avant le DDL

                    -- ---------------------------------------------------------
                    -- Phase DROP PARTITION avec reconstruction des index globaux
                    -- UPDATE GLOBAL INDEXES : rebuild PK_EXECUTIONS et autres index globaux
                    -- sans les invalider — service disponible pendant toute l'opération.
                    -- EXECUTION_STEPS cascade automatiquement (Reference Partitioning V085).
                    -- ---------------------------------------------------------
                    EXECUTE IMMEDIATE
                        'ALTER TABLE EXECUTIONS DROP PARTITION ' || r.PARTITION_NAME
                        || ' UPDATE GLOBAL INDEXES';

                    log_maintenance('EXECUTIONS', r.PARTITION_NAME, 'DROP', 'SUCCESS', 0,
                        'EXECUTION_STEPS cascade automatique (Reference Partitioning V085)');

                    DBMS_OUTPUT.PUT_LINE('  ✓ EXECUTIONS.' || r.PARTITION_NAME || ' dropped.');

                ELSE
                    -- Mode DRY_RUN : log uniquement, pas de modification
                    -- Estimer le nombre de lignes (pour information)
                    BEGIN
                        EXECUTE IMMEDIATE
                            'SELECT COUNT(*) FROM EXECUTIONS PARTITION (' || r.PARTITION_NAME || ')'
                            INTO v_rows_estimate;
                    EXCEPTION
                        WHEN OTHERS THEN v_rows_estimate := -1;
                    END;

                    log_maintenance('EXECUTIONS', r.PARTITION_NAME, 'DROP', 'DRY_RUN', 1,
                        'Estimated rows: ' || v_rows_estimate
                        || ' | HIGH_VALUE: ' || TO_CHAR(v_part_date, 'YYYY-MM-DD'));
                END IF;

            ELSE
                -- Partition dans la fenêtre de rétention → conserver
                DBMS_OUTPUT.PUT_LINE(
                    'KEEP ' || r.PARTITION_NAME
                    || ' (HIGH_VALUE=' || TO_CHAR(v_part_date, 'YYYY-MM-DD')
                    || ' > cutoff=' || TO_CHAR(v_cutoff_date, 'YYYY-MM-DD') || ')'
                );
            END IF;

        END LOOP;

        COMMIT;  -- Commit final du log

        DBMS_OUTPUT.PUT_LINE('purge_executions completed.');

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            DBMS_OUTPUT.PUT_LINE('ERROR in purge_executions: ' || SQLERRM);
            -- Log l'erreur dans IDP_MAINTENANCE_LOG si possible
            BEGIN
                log_maintenance('EXECUTIONS', 'UNKNOWN', 'DROP', 'ERROR', p_dry_run,
                    SUBSTR(SQLERRM, 1, 500));
                COMMIT;
            EXCEPTION
                WHEN OTHERS THEN NULL;
            END;
            RAISE;
    END purge_executions;

    -- ===========================================================
    -- Implémentation : purge_audit_log
    -- ⚠️  SOC1/NFR8 : p_dry_run=1 par défaut
    -- DROP PARTITION contourne TRG_AUDIT_LOG_IMMUTABLE (DDL ≠ DML).
    -- Valider conformité réglementaire avant activation en production.
    -- ===========================================================
    PROCEDURE purge_audit_log(
        p_retention_months  IN NUMBER  DEFAULT 12,
        p_dry_run           IN NUMBER  DEFAULT 1
    ) IS
        v_cutoff_date   DATE;
        v_part_date     DATE;
        v_rows_estimate NUMBER;
    BEGIN
        v_cutoff_date := ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -p_retention_months);

        DBMS_OUTPUT.PUT_LINE(
            'purge_audit_log — cutoff: ' || TO_CHAR(v_cutoff_date, 'YYYY-MM-DD')
            || ' | dry_run: ' || p_dry_run
        );

        -- Avertissement SOC1/NFR8 systématique dans les logs
        IF p_dry_run = 0 THEN
            DBMS_OUTPUT.PUT_LINE(
                '⚠️  WARNING: AUDIT_LOG purge activated (p_dry_run=0). '
                || 'Ensure SOC1/NFR8 compliance has been validated with the compliance team '
                || 'before executing in production. Data loss is IRREVERSIBLE.'
            );
            log_maintenance('AUDIT_LOG', 'ALL', 'PURGE_ACTIVATED', 'WARNING', 0,
                'SOC1/NFR8: purge activated. Compliance validation required.');
        END IF;

        FOR r IN (
            SELECT PARTITION_NAME, HIGH_VALUE
            FROM   USER_TAB_PARTITIONS
            WHERE  TABLE_NAME = 'AUDIT_LOG'
            AND    PARTITION_NAME != 'P_INITIAL'  -- partition initiale de migration V086 à exclure
            ORDER BY PARTITION_POSITION
        ) LOOP
            v_part_date := get_partition_date(r.HIGH_VALUE);

            IF v_part_date IS NULL THEN
                DBMS_OUTPUT.PUT_LINE(
                    'SKIP ' || r.PARTITION_NAME || ' — HIGH_VALUE non convertible en date'
                );
                log_maintenance('AUDIT_LOG', r.PARTITION_NAME, 'SKIP', 'SKIPPED',
                    p_dry_run, 'HIGH_VALUE non convertible: ' || SUBSTR(r.HIGH_VALUE, 1, 100));
                CONTINUE;
            END IF;

            IF v_part_date <= v_cutoff_date THEN

                DBMS_OUTPUT.PUT_LINE(
                    (CASE WHEN p_dry_run = 1 THEN '[DRY_RUN] ' ELSE '[EXECUTE] ' END)
                    || 'DROP PARTITION AUDIT_LOG.' || r.PARTITION_NAME
                    || ' (HIGH_VALUE=' || TO_CHAR(v_part_date, 'YYYY-MM-DD') || ')'
                );

                IF p_dry_run = 0 THEN
                    -- AUDIT_LOG n'a pas de FK entrante — DROP direct sans pré-requis DML.
                    -- UPDATE GLOBAL INDEXES : rebuild PK_AUDIT_LOG + IDX_AUDIT_LOG_CORRELATION
                    EXECUTE IMMEDIATE
                        'ALTER TABLE AUDIT_LOG DROP PARTITION ' || r.PARTITION_NAME
                        || ' UPDATE GLOBAL INDEXES';

                    log_maintenance('AUDIT_LOG', r.PARTITION_NAME, 'DROP', 'SUCCESS', 0, NULL);

                    DBMS_OUTPUT.PUT_LINE('  ✓ AUDIT_LOG.' || r.PARTITION_NAME || ' dropped.');

                ELSE
                    BEGIN
                        EXECUTE IMMEDIATE
                            'SELECT COUNT(*) FROM AUDIT_LOG PARTITION (' || r.PARTITION_NAME || ')'
                            INTO v_rows_estimate;
                    EXCEPTION
                        WHEN OTHERS THEN v_rows_estimate := -1;
                    END;

                    log_maintenance('AUDIT_LOG', r.PARTITION_NAME, 'DROP', 'DRY_RUN', 1,
                        'Estimated rows: ' || v_rows_estimate
                        || ' | HIGH_VALUE: ' || TO_CHAR(v_part_date, 'YYYY-MM-DD'));
                END IF;

            ELSE
                DBMS_OUTPUT.PUT_LINE(
                    'KEEP ' || r.PARTITION_NAME
                    || ' (HIGH_VALUE=' || TO_CHAR(v_part_date, 'YYYY-MM-DD')
                    || ' > cutoff=' || TO_CHAR(v_cutoff_date, 'YYYY-MM-DD') || ')'
                );
            END IF;

        END LOOP;

        COMMIT;

        DBMS_OUTPUT.PUT_LINE('purge_audit_log completed.');

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            DBMS_OUTPUT.PUT_LINE('ERROR in purge_audit_log: ' || SQLERRM);
            BEGIN
                log_maintenance('AUDIT_LOG', 'UNKNOWN', 'DROP', 'ERROR', p_dry_run,
                    SUBSTR(SQLERRM, 1, 500));
                COMMIT;
            EXCEPTION
                WHEN OTHERS THEN NULL;
            END;
            RAISE;
    END purge_audit_log;

    -- ===========================================================
    -- Implémentation : purge_old_partitions (point d'entrée principal)
    -- ===========================================================
    PROCEDURE purge_old_partitions(
        p_retention_executions  IN NUMBER  DEFAULT 24,
        p_retention_audit_log   IN NUMBER  DEFAULT 12,
        p_dry_run               IN NUMBER  DEFAULT 1
    ) IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(
            '=== PKG_IDP_MAINTENANCE.purge_old_partitions ==='
            || ' | retention_executions=' || p_retention_executions
            || ' | retention_audit_log=' || p_retention_audit_log
            || ' | dry_run=' || p_dry_run
        );

        -- Purge EXECUTIONS (cascade automatique EXECUTION_STEPS via Reference Partitioning)
        purge_executions(
            p_retention_months => p_retention_executions,
            p_dry_run          => p_dry_run
        );

        -- Purge AUDIT_LOG (indépendante, pas de FK entrante)
        -- ⚠️  p_dry_run=1 par défaut — conformité SOC1/NFR8 obligatoire avant activation
        purge_audit_log(
            p_retention_months => p_retention_audit_log,
            p_dry_run          => p_dry_run
        );

        DBMS_OUTPUT.PUT_LINE('=== purge_old_partitions completed ===');
    END purge_old_partitions;

END PKG_IDP_MAINTENANCE;
/

-- ============================================================
-- PHASE 4 : Valider l'installation
-- ============================================================
DECLARE
    v_pkg_spec_count   NUMBER;
    v_pkg_body_count   NUMBER;
    v_table_count      NUMBER;
    v_index_count      NUMBER;
BEGIN
    -- Vérifier que le package spec est compilé et valide
    SELECT COUNT(*) INTO v_pkg_spec_count
    FROM USER_OBJECTS
    WHERE OBJECT_NAME = 'PKG_IDP_MAINTENANCE'
      AND OBJECT_TYPE = 'PACKAGE'
      AND STATUS = 'VALID';

    IF v_pkg_spec_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20010,
            'PKG_IDP_MAINTENANCE PACKAGE spec is missing or INVALID. Check compilation errors.');
    END IF;

    -- Vérifier que le package body est compilé et valide
    SELECT COUNT(*) INTO v_pkg_body_count
    FROM USER_OBJECTS
    WHERE OBJECT_NAME = 'PKG_IDP_MAINTENANCE'
      AND OBJECT_TYPE = 'PACKAGE BODY'
      AND STATUS = 'VALID';

    IF v_pkg_body_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20011,
            'PKG_IDP_MAINTENANCE PACKAGE BODY is missing or INVALID. Check compilation errors.');
    END IF;

    -- Vérifier que IDP_MAINTENANCE_LOG existe
    SELECT COUNT(*) INTO v_table_count
    FROM USER_TABLES WHERE TABLE_NAME = 'IDP_MAINTENANCE_LOG';

    IF v_table_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20012,
            'IDP_MAINTENANCE_LOG table is missing after V087 Phase 1.');
    END IF;

    -- Vérifier que l'index IDX_MAINT_LOG_EXECUTED_AT existe
    SELECT COUNT(*) INTO v_index_count
    FROM USER_INDEXES
    WHERE TABLE_NAME = 'IDP_MAINTENANCE_LOG'
      AND INDEX_NAME = 'IDX_MAINT_LOG_EXECUTED_AT';

    IF v_index_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20013,
            'IDX_MAINT_LOG_EXECUTED_AT index is missing on IDP_MAINTENANCE_LOG.');
    END IF;

    DBMS_OUTPUT.PUT_LINE(
        'V087 installation validated successfully:'
        || ' PKG_IDP_MAINTENANCE (spec+body=VALID)'
        || ', IDP_MAINTENANCE_LOG (table+index OK)'
    );
END;
/

-- ============================================================
-- COMMENTAIRES FINAUX
-- ============================================================
COMMENT ON TABLE IDP_MAINTENANCE_LOG IS
    'Journal des opérations de purge des partitions Oracle. Story 40.5. '
    || 'Alimentée par PKG_IDP_MAINTENANCE. Chaque DROP (ou simulation DRY_RUN) est tracé.';
