-- V089: Create AUTH_USER table for django.contrib.auth
-- Django admin and AuthenticationMiddleware use auth.User which maps to AUTH_USER.
-- idp_auth.User maps to USERS (V001); this table is for Django's built-in auth (admin login, etc.).

CREATE TABLE AUTH_USER (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PASSWORD        VARCHAR2(128) NOT NULL,
    LAST_LOGIN      TIMESTAMP,
    IS_SUPERUSER    NUMBER(1) DEFAULT 0 NOT NULL,
    USERNAME        VARCHAR2(150) NOT NULL,
    FIRST_NAME      VARCHAR2(150),
    LAST_NAME       VARCHAR2(150),
    EMAIL          VARCHAR2(254),
    IS_STAFF        NUMBER(1) DEFAULT 0 NOT NULL,
    IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL,
    DATE_JOINED     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_AUTH_USER_IS_SUPERUSER CHECK (IS_SUPERUSER IN (0, 1)),
    CONSTRAINT CK_AUTH_USER_IS_STAFF    CHECK (IS_STAFF IN (0, 1)),
    CONSTRAINT CK_AUTH_USER_IS_ACTIVE   CHECK (IS_ACTIVE IN (0, 1))
);

CREATE UNIQUE INDEX UK_AUTH_USER_USERNAME ON AUTH_USER(USERNAME);
