-- V090: Create DJANGO_SESSION table for django.contrib.sessions
-- Used by SessionMiddleware for admin login and session storage.

CREATE TABLE DJANGO_SESSION (
    SESSION_KEY   VARCHAR2(40) NOT NULL,
    SESSION_DATA  CLOB NOT NULL,
    EXPIRE_DATE   TIMESTAMP NOT NULL,
    CONSTRAINT PK_DJANGO_SESSION PRIMARY KEY (SESSION_KEY)
);

CREATE INDEX IDX_DJANGO_SESSION_EXPIRE_DATE ON DJANGO_SESSION(EXPIRE_DATE);
