-- V091: Create API_KEYS table for idp_auth.APIKey
-- Stores API keys for programmatic access (JWT alternative).

CREATE TABLE API_KEYS (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    KEY_HASH        VARCHAR2(64) NOT NULL,
    NAME            VARCHAR2(255) DEFAULT '' NOT NULL,
    SCOPE           VARCHAR2(50),
    EXPIRES_AT      TIMESTAMP,
    IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_API_KEYS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT CK_API_KEYS_IS_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE UNIQUE INDEX UK_API_KEYS_KEY_HASH ON API_KEYS(KEY_HASH);
CREATE INDEX IDX_API_KEYS_USER_ID ON API_KEYS(USER_ID);
