-- V092: Create AUTH_GROUP and AUTH_USER_GROUPS for django.contrib.auth
-- AUTH_GROUP: groups for permission management
-- AUTH_USER_GROUPS: M2M through table linking auth_user to auth_group

CREATE TABLE AUTH_GROUP (
    ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(150) NOT NULL,
    CONSTRAINT UK_AUTH_GROUP_NAME UNIQUE (NAME)
);

CREATE TABLE AUTH_USER_GROUPS (
    ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID  NUMBER NOT NULL,
    GROUP_ID NUMBER NOT NULL,
    CONSTRAINT FK_AUTH_USER_GROUPS_USER  FOREIGN KEY (USER_ID)  REFERENCES AUTH_USER(ID) ON DELETE CASCADE,
    CONSTRAINT FK_AUTH_USER_GROUPS_GROUP FOREIGN KEY (GROUP_ID) REFERENCES AUTH_GROUP(ID) ON DELETE CASCADE,
    CONSTRAINT UK_AUTH_USER_GROUPS_USER_GROUP UNIQUE (USER_ID, GROUP_ID)
);

CREATE INDEX IDX_AUTH_USER_GROUPS_USER_ID  ON AUTH_USER_GROUPS(USER_ID);
CREATE INDEX IDX_AUTH_USER_GROUPS_GROUP_ID ON AUTH_USER_GROUPS(GROUP_ID);
