-- V093: Create DJANGO_CONTENT_TYPE, AUTH_PERMISSION, AUTH_USER_USER_PERMISSIONS
-- Required by django.contrib.contenttypes and django.contrib.auth

-- ContentType (django.contrib.contenttypes)
CREATE TABLE DJANGO_CONTENT_TYPE (
    ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_LABEL VARCHAR2(100) NOT NULL,
    MODEL     VARCHAR2(100) NOT NULL,
    CONSTRAINT UK_DJANGO_CONTENT_TYPE_APP_MODEL UNIQUE (APP_LABEL, MODEL)
);

-- Permission (django.contrib.auth)
CREATE TABLE AUTH_PERMISSION (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME            VARCHAR2(255) NOT NULL,
    CONTENT_TYPE_ID NUMBER NOT NULL,
    CODENAME        VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_AUTH_PERMISSION_CONTENT_TYPE FOREIGN KEY (CONTENT_TYPE_ID) REFERENCES DJANGO_CONTENT_TYPE(ID) ON DELETE CASCADE,
    CONSTRAINT UK_AUTH_PERMISSION_CONTENT_CODENAME UNIQUE (CONTENT_TYPE_ID, CODENAME)
);

CREATE INDEX IDX_AUTH_PERMISSION_CONTENT_TYPE ON AUTH_PERMISSION(CONTENT_TYPE_ID);

-- M2M user ↔ permission
CREATE TABLE AUTH_USER_USER_PERMISSIONS (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID       NUMBER NOT NULL,
    PERMISSION_ID NUMBER NOT NULL,
    CONSTRAINT FK_AUTH_USER_PERM_USER       FOREIGN KEY (USER_ID)       REFERENCES AUTH_USER(ID) ON DELETE CASCADE,
    CONSTRAINT FK_AUTH_USER_PERM_PERMISSION  FOREIGN KEY (PERMISSION_ID) REFERENCES AUTH_PERMISSION(ID) ON DELETE CASCADE,
    CONSTRAINT UK_AUTH_USER_PERM_USER_PERM UNIQUE (USER_ID, PERMISSION_ID)
);

CREATE INDEX IDX_AUTH_USER_PERM_USER_ID       ON AUTH_USER_USER_PERMISSIONS(USER_ID);
CREATE INDEX IDX_AUTH_USER_PERM_PERMISSION_ID ON AUTH_USER_USER_PERMISSIONS(PERMISSION_ID);
