-- V098: Add health check columns to INTEGRATIONS table
-- Story 51.1: Integration health check (periodic + manual test)
-- Aligns Oracle schema with Django integrations/0008_integration_health_check_fields

ALTER TABLE INTEGRATIONS ADD HEALTH_STATUS VARCHAR2(10) DEFAULT 'unknown' NOT NULL;
ALTER TABLE INTEGRATIONS ADD HEALTH_CHECKED_AT TIMESTAMP NULL;
ALTER TABLE INTEGRATIONS ADD HEALTH_ERROR_MESSAGE CLOB NULL;

ALTER TABLE INTEGRATIONS ADD CONSTRAINT CK_INTEGRATIONS_HEALTH_STATUS CHECK (
    HEALTH_STATUS IN ('ok', 'error', 'unknown')
);

CREATE INDEX IDX_INTEGRATIONS_HEALTH_STATUS ON INTEGRATIONS(HEALTH_STATUS);

COMMENT ON COLUMN INTEGRATIONS.HEALTH_STATUS IS 'Health check result: ok, error, unknown (Story 51.1)';
COMMENT ON COLUMN INTEGRATIONS.HEALTH_CHECKED_AT IS 'Last health check timestamp';
COMMENT ON COLUMN INTEGRATIONS.HEALTH_ERROR_MESSAGE IS 'Error message when health_status=error';
