-- V112: Add IaC sync tracking columns to all IaC-managed tables
-- Story 64.11 - Infrastructure as Code: sync tracking

ALTER TABLE ACTIONS_CATALOG ADD LAST_SYNCED_AT TIMESTAMP NULL;
ALTER TABLE ACTIONS_CATALOG ADD LAST_SYNCED_HASH VARCHAR2(64) NULL;

ALTER TABLE INTEGRATIONS ADD LAST_SYNCED_AT TIMESTAMP NULL;
ALTER TABLE INTEGRATIONS ADD LAST_SYNCED_HASH VARCHAR2(64) NULL;

ALTER TABLE BUSINESS_RULE_POLICIES ADD LAST_SYNCED_AT TIMESTAMP NULL;
ALTER TABLE BUSINESS_RULE_POLICIES ADD LAST_SYNCED_HASH VARCHAR2(64) NULL;

ALTER TABLE PROFILES ADD LAST_SYNCED_AT TIMESTAMP NULL;
ALTER TABLE PROFILES ADD LAST_SYNCED_HASH VARCHAR2(64) NULL;

ALTER TABLE INTEGRATION_TYPE_CATALOGUE ADD LAST_SYNCED_AT TIMESTAMP NULL;
ALTER TABLE INTEGRATION_TYPE_CATALOGUE ADD LAST_SYNCED_HASH VARCHAR2(64) NULL;

ALTER TABLE REF_ENGINES ADD LAST_SYNCED_AT TIMESTAMP NULL;
ALTER TABLE REF_ENGINES ADD LAST_SYNCED_HASH VARCHAR2(64) NULL;

ALTER TABLE REF_CATEGORIES ADD LAST_SYNCED_AT TIMESTAMP NULL;
ALTER TABLE REF_CATEGORIES ADD LAST_SYNCED_HASH VARCHAR2(64) NULL;

ALTER TABLE CORE_FEATURE_FLAGS ADD LAST_SYNCED_AT TIMESTAMP NULL;
ALTER TABLE CORE_FEATURE_FLAGS ADD LAST_SYNCED_HASH VARCHAR2(64) NULL;
