-- Story 63.9: Déclarer les outputs par action — FK OUTPUT_SCHEMA_ID sur ACTIONS_CATALOG
ALTER TABLE ACTIONS_CATALOG ADD (
    OUTPUT_SCHEMA_ID NUMBER(19)
);

ALTER TABLE ACTIONS_CATALOG ADD CONSTRAINT FK_ACTION_OUTPUT_SCHEMA
    FOREIGN KEY (OUTPUT_SCHEMA_ID)
    REFERENCES OUTPUT_SCHEMAS(ID)
    ON DELETE SET NULL;

CREATE INDEX IDX_ACTION_OUTPUT_SCHEMA ON ACTIONS_CATALOG(OUTPUT_SCHEMA_ID);

COMMENT ON COLUMN ACTIONS_CATALOG.OUTPUT_SCHEMA_ID IS 'FK vers OUTPUT_SCHEMAS — schéma d''output déclaré par l''admin pour cette action (Story 63.9)';
