-- V117: Add missing audit types to align Oracle CK_AUDIT_LOG_ACTION_TYPE with Django
-- Fixes ORA-02290 when Django emits audit rows with types added in core/migrations 0005-0010.
-- Story 66-16: SCHEDULED_EXECUTION_RECURRING_ENABLED (toggle re-activation of recurring pattern)
-- Epic 57: EXECUTION_STEP_POLICY_* (gate approval), POLICY_* (business rule policies)
-- Polling: EXECUTION_POLLING_EXHAUSTED
-- Story 66-17: API_KEY_CREATED, API_KEY_REVOKED (API key lifecycle)
-- Ref: docs/backend/migration/etat-des-lieux-migrations-bd.md

ALTER TABLE AUDIT_LOG DROP CONSTRAINT CK_AUDIT_LOG_ACTION_TYPE;

ALTER TABLE AUDIT_LOG ADD CONSTRAINT CK_AUDIT_LOG_ACTION_TYPE CHECK (
    ACTION_TYPE IN (
        -- Action lifecycle
        'ACTION_CREATED', 'ACTION_UPDATED', 'ACTION_PUBLISHED',
        'ACTION_DISABLED', 'ACTION_DISABLED_INTEGRATION_DELETED', 'ACTION_ENABLED', 'ACTION_DELETED',
        'ACTION_DEACTIVATED', 'ACTION_REACTIVATED',

        -- Profile lifecycle
        'PROFILE_CREATED', 'PROFILE_UPDATED', 'PROFILE_DELETED',
        'PROFILE_UPDATE_REJECTED',

        -- Integration lifecycle
        'INTEGRATION_CREATED', 'INTEGRATION_UPDATED', 'INTEGRATION_DELETED',
        'INTEGRATION_HEALTH_CHECK_TESTED',

        -- Integration type catalogue
        'INTEGRATION_TYPE_CREATED', 'INTEGRATION_TYPE_UPDATED',
        'INTEGRATION_ACTION_CREATED', 'INTEGRATION_ACTION_UPDATED',

        -- Integration status / migration
        'INTEGRATION_STATUS_UPDATED', 'INTEGRATION_MARKED_LEGACY',

        -- Execution lifecycle
        'EXECUTION_SUBMITTED', 'EXECUTION_STARTED', 'EXECUTION_RUNNING',
        'EXECUTION_COMPLETED', 'EXECUTION_FAILED', 'EXECUTION_CANCELLED',
        'EXECUTION_PENDING_APPROVAL', 'EXECUTION_APPROVED', 'EXECUTION_REJECTED',
        'EXECUTION_TARGET_FORBIDDEN', 'EXECUTION_INTEGRATION_ERROR',
        'EXECUTION_BLOCKED_INVALID_INTEGRATION', 'EXECUTION_DEPRECATED_INTEGRATION_WARNING',
        'WORKFLOW_STEP_BLOCKED_INVALID_INTEGRATION',

        -- ServiceNow change
        'SERVICENOW_CHANGE_CREATED',

        -- Remediation / auto-remediation
        'REMEDIATION_EXECUTION_CREATED',
        'AUTO_REMEDIATION_TRIGGERED', 'AUTO_REMEDIATION_SUCCESS', 'AUTO_REMEDIATION_FAILED',

        -- Scheduled executions
        'SCHEDULED_EXECUTION_CREATED', 'SCHEDULED_EXECUTION_RECURRING_CREATED',
        'SCHEDULED_EXECUTION_EXECUTED', 'SCHEDULED_EXECUTION_CANCELLED',
        'SCHEDULED_EXECUTION_RECURRING_DISABLED',
        'SCHEDULED_EXECUTION_RECURRING_ENABLED',  -- V117: Story 66-16 toggle re-activation
        'SCHEDULED_EXECUTION_CELERY_TRIGGERED',

        -- User / Auth / Favorites
        'USER_CREATED', 'USER_UPDATED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_REFRESH',
        'API_KEY_TOKEN_EXCHANGE', 'API_KEY_CREATED', 'API_KEY_REVOKED',
        'FAVORITE_ADDED', 'FAVORITE_REMOVED', 'SERVICE_LOGIN',
        'AUTH_DEV_BYPASS_LOGIN',

        -- Execution step retry
        'EXECUTION_STEP_RETRY_ATTEMPT', 'EXECUTION_STEP_RETRY_SUCCESS',
        'EXECUTION_STEP_RETRY_EXHAUSTED', 'EXECUTION_STEP_RETRY_ABORTED',

        -- Condition gates / policy approval (Epic 57)
        'EXECUTION_STEP_WAITING',
        'EXECUTION_STEP_GATE_SATISFIED',
        'EXECUTION_STEP_GATE_TIMEOUT',
        'EXECUTION_STEP_POLICY_APPROVAL_REQUIRED',
        'EXECUTION_STEP_POLICY_AUTO_APPROVED',
        'EXECUTION_STEP_POLICY_EVALUATION_FAILED',

        -- Story 57.15: Workflow schedule step
        'WORKFLOW_STEP_SCHEDULE_CREATED',

        -- Feature flags
        'FEATURE_FLAG_CREATED', 'FEATURE_FLAG_UPDATED',

        -- Business rule policies (Epic 57)
        'POLICY_CREATED', 'POLICY_UPDATED', 'POLICY_DELETED',

        -- Execution polling
        'EXECUTION_POLLING_EXHAUSTED',

        -- Story 64.x: IaC Config Sync import actions
        'CONFIG_SYNC_REFERENCE_IMPORT', 'CONFIG_SYNC_TAGS_IMPORT',
        'CONFIG_SYNC_FEATURE_FLAGS_IMPORT', 'CONFIG_SYNC_INTEGRATION_TYPE_IMPORT',
        'CONFIG_SYNC_INTEGRATION_IMPORT', 'CONFIG_SYNC_POLICY_IMPORT',
        'CONFIG_SYNC_ACTION_IMPORT'
    )
);

COMMENT ON COLUMN AUDIT_LOG.ACTION_TYPE IS 'V117: SCHEDULED_EXECUTION_RECURRING_ENABLED, EXECUTION_STEP_POLICY_*, POLICY_*, EXECUTION_POLLING_EXHAUSTED, API_KEY_CREATED, API_KEY_REVOKED added. Aligns with Django core/migrations.';
