-- V124: Table WORKFLOW_COMMANDS — commandes durables
-- Story 78.4 — Command Store pour orchestration asynchrone
--
-- L'API écrit une commande durable (approve, reject, cancel, signals)
-- et retourne rapidement. Un processor séparé traite les commandes
-- en FIFO via polling avec SELECT ... FOR UPDATE SKIP LOCKED.

CREATE TABLE WORKFLOW_COMMANDS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EXECUTION_ID    NUMBER NOT NULL,
    COMMAND_TYPE    VARCHAR2(50) NOT NULL,
    PAYLOAD         CLOB,
    STATUS          VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    PROCESSED_AT    TIMESTAMP,
    CREATED_BY      VARCHAR2(255),
    ERROR_MESSAGE   CLOB,
    CONSTRAINT FK_WF_CMD_EXECUTION FOREIGN KEY (EXECUTION_ID)
        REFERENCES EXECUTIONS(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_WF_CMD_STATUS CHECK (STATUS IN ('pending', 'processed', 'failed')),
    CONSTRAINT CHK_WF_CMD_TYPE CHECK (COMMAND_TYPE IN (
        'approve', 'reject', 'cancel', 'timeout_signal', 'resume_signal'
    ))
);

CREATE INDEX IDX_WF_CMD_STATUS_CREATED ON WORKFLOW_COMMANDS(STATUS, CREATED_AT);
CREATE INDEX IDX_WF_CMD_EXECUTION ON WORKFLOW_COMMANDS(EXECUTION_ID);

COMMENT ON TABLE WORKFLOW_COMMANDS IS 'Commandes workflow durables — persistées avant traitement (approve, reject, cancel, signals).';
COMMENT ON COLUMN WORKFLOW_COMMANDS.EXECUTION_ID IS 'FK vers EXECUTIONS — exécution cible de la commande.';
COMMENT ON COLUMN WORKFLOW_COMMANDS.COMMAND_TYPE IS 'Type de commande: approve, reject, cancel, timeout_signal, resume_signal.';
COMMENT ON COLUMN WORKFLOW_COMMANDS.PAYLOAD IS 'Données JSON de la commande (step_id, comment, user_id, etc.).';
COMMENT ON COLUMN WORKFLOW_COMMANDS.STATUS IS 'Statut: pending (en attente), processed (traité), failed (échoué).';
COMMENT ON COLUMN WORKFLOW_COMMANDS.CREATED_AT IS 'Horodatage de création de la commande.';
COMMENT ON COLUMN WORKFLOW_COMMANDS.PROCESSED_AT IS 'Horodatage de traitement effectif. NULL si pending.';
COMMENT ON COLUMN WORKFLOW_COMMANDS.CREATED_BY IS 'Identifiant utilisateur ayant émis la commande.';
COMMENT ON COLUMN WORKFLOW_COMMANDS.ERROR_MESSAGE IS 'Message d''erreur si status=failed.';
