-- V134: Add CHECK (IS JSON) constraints on all Tier 2 CLOB/JSON columns (Story 78.13)
-- Ensures data integrity at the DB level for 16 columns across 10 tables.
-- Each ALTER is wrapped in an idempotent PL/SQL block:
--   - SQLCODE -2264: constraint name already exists → skip (idempotent)
--   - SQLCODE -2293: existing data violates constraint → re-raise (must fix data first)

-- 1. EXECUTIONS.PARAMETERS
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EXECUTIONS ADD CONSTRAINT CK_EXEC_PARAMETERS_JSON CHECK (PARAMETERS IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 2. EXECUTION_STEPS.OUTPUT
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EXECUTION_STEPS ADD CONSTRAINT CK_EXECSTEP_OUTPUT_JSON CHECK (OUTPUT IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 3. EXECUTION_TARGETS.TARGET_METADATA
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EXECUTION_TARGETS ADD CONSTRAINT CK_EXECTGT_TARGET_METADATA_JSON CHECK (TARGET_METADATA IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 4. INTEGRATIONS.CONFIG
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE INTEGRATIONS ADD CONSTRAINT CK_INTEG_CONFIG_JSON CHECK (CONFIG IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 5. SCHEDULED_EXECUTIONS.PARAMETERS
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE SCHEDULED_EXECUTIONS ADD CONSTRAINT CK_SCHEDEXEC_PARAMETERS_JSON CHECK (PARAMETERS IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 6. RECURRING_PATTERNS.PATTERN_CONFIG
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE RECURRING_PATTERNS ADD CONSTRAINT CK_RECPAT_PATTERN_CONFIG_JSON CHECK (PATTERN_CONFIG IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 7. INTEGRATION_ACTIONS.REQUIRED_PARAMS
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE INTEGRATION_ACTIONS ADD CONSTRAINT CK_INTACT_REQUIRED_PARAMS_JSON CHECK (REQUIRED_PARAMS IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 8. INTEGRATION_ACTIONS.OPTIONAL_PARAMS
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE INTEGRATION_ACTIONS ADD CONSTRAINT CK_INTACT_OPTIONAL_PARAMS_JSON CHECK (OPTIONAL_PARAMS IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 9. INTEGRATION_ACTIONS.RESPONSE_FORMAT
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE INTEGRATION_ACTIONS ADD CONSTRAINT CK_INTACT_RESPONSE_FORMAT_JSON CHECK (RESPONSE_FORMAT IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 10. ACTIONS_CATALOG.PARAMETERS_SCHEMA
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ACTIONS_CATALOG ADD CONSTRAINT CK_ACTCAT_PARAMETERS_SCHEMA_JSON CHECK (PARAMETERS_SCHEMA IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 11. ACTIONS_CATALOG.IMPACT_RULES
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ACTIONS_CATALOG ADD CONSTRAINT CK_ACTCAT_IMPACT_RULES_JSON CHECK (IMPACT_RULES IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 12. ACTIONS_CATALOG.EXECUTION_STEPS
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ACTIONS_CATALOG ADD CONSTRAINT CK_ACTCAT_EXECUTION_STEPS_JSON CHECK (EXECUTION_STEPS IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 13. ACTIONS_CATALOG.REMEDIATION_RULES
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ACTIONS_CATALOG ADD CONSTRAINT CK_ACTCAT_REMEDIATION_RULES_JSON CHECK (REMEDIATION_RULES IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 14. ACTIONS_CATALOG.BUSINESS_RULE_POLICIES
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ACTIONS_CATALOG ADD CONSTRAINT CK_ACTCAT_BIZ_RULE_POLICIES_JSON CHECK (BUSINESS_RULE_POLICIES IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 15. BUSINESS_RULE_POLICIES.POLICY_JSON
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BUSINESS_RULE_POLICIES ADD CONSTRAINT CK_BRP_POLICY_JSON_JSON CHECK (POLICY_JSON IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/

-- 16. WORKFLOW_COMMANDS.PAYLOAD
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE WORKFLOW_COMMANDS ADD CONSTRAINT CK_WFCMD_PAYLOAD_JSON CHECK (PAYLOAD IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; -- ORA-02264: constraint name already used in schema → skip
    ELSIF SQLCODE = -2293 THEN RAISE; -- ORA-02293: existing data violates constraint → must fix data first
    ELSE RAISE;
    END IF;
END;
/
