# Generated by Django 5.2.11 on 2026-02-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='TIMESTAMP')),
                ('user_id', models.CharField(db_column='USER_ID', max_length=100)),
                ('action_type', models.CharField(choices=[('ACTION_CREATED', 'Action Created'), ('ACTION_UPDATED', 'Action Updated'), ('ACTION_PUBLISHED', 'Action Published'), ('ACTION_DISABLED', 'Action Disabled'), ('ACTION_ENABLED', 'Action Enabled')], db_column='ACTION_TYPE', max_length=50)),
                ('entity_type', models.CharField(choices=[('action', 'Action'), ('user', 'User'), ('permission', 'Permission'), ('execution', 'Execution')], db_column='ENTITY_TYPE', max_length=50)),
                ('entity_id', models.BigIntegerField(db_column='ENTITY_ID')),
                ('details', models.TextField(blank=True, db_column='DETAILS', null=True)),
                ('ip_address', models.CharField(blank=True, db_column='IP_ADDRESS', max_length=45, null=True)),
            ],
            options={
                'db_table': 'AUDIT_LOG',
                'ordering': ['-timestamp'],
            },
        ),
    ]
