# Generated by Django 5.2.11 on 2026-02-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="correlation_id",
            field=models.CharField(
                blank=True, db_column="CORRELATION_ID", max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("ACTION_CREATED", "Action Created"),
                    ("ACTION_UPDATED", "Action Updated"),
                    ("ACTION_PUBLISHED", "Action Published"),
                    ("ACTION_DISABLED", "Action Disabled"),
                    ("ACTION_ENABLED", "Action Enabled"),
                    ("ACTION_DELETED", "Action Deleted"),
                    ("PROFILE_CREATED", "Profile Created"),
                    ("PROFILE_UPDATED", "Profile Updated"),
                    ("PROFILE_DELETED", "Profile Deleted"),
                    ("INTEGRATION_CREATED", "Integration Created"),
                    ("INTEGRATION_UPDATED", "Integration Updated"),
                    ("INTEGRATION_DELETED", "Integration Deleted"),
                    ("EXECUTION_SUBMITTED", "Execution Submitted"),
                    ("EXECUTION_RUNNING", "Execution Running"),
                    ("EXECUTION_COMPLETED", "Execution Completed"),
                    ("EXECUTION_FAILED", "Execution Failed"),
                    ("EXECUTION_CANCELLED", "Execution Cancelled"),
                    ("EXECUTION_PENDING_APPROVAL", "Execution Pending Approval"),
                    ("EXECUTION_REJECTED", "Execution Rejected"),
                    ("EXECUTION_TARGET_FORBIDDEN", "Execution Target Forbidden"),
                    ("SCHEDULED_EXECUTION_CREATED", "Scheduled Execution Created"),
                    (
                        "SCHEDULED_EXECUTION_RECURRING_CREATED",
                        "Scheduled Execution Recurring Created",
                    ),
                    ("SCHEDULED_EXECUTION_EXECUTED", "Scheduled Execution Executed"),
                    ("SCHEDULED_EXECUTION_CANCELLED", "Scheduled Execution Cancelled"),
                    (
                        "SCHEDULED_EXECUTION_RECURRING_DISABLED",
                        "Scheduled Execution Recurring Disabled",
                    ),
                    ("USER_CREATED", "User Created"),
                    ("USER_UPDATED", "User Updated"),
                    ("USER_LOGIN", "User Login"),
                    ("USER_LOGOUT", "User Logout"),
                    ("USER_REFRESH", "User Refresh Token"),
                    ("FAVORITE_ADDED", "Favorite Added"),
                    ("FAVORITE_REMOVED", "Favorite Removed"),
                ],
                db_column="ACTION_TYPE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("action", "Action"),
                    ("user", "User"),
                    ("permission", "Permission"),
                    ("execution", "Execution"),
                    ("integration", "Integration"),
                    ("scheduled_execution", "Scheduled Execution"),
                    ("profile", "Profile"),
                ],
                db_column="ENTITY_TYPE",
                max_length=50,
            ),
        ),
    ]
