# Generated by Django 5.2.11 on 2026-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditlog_correlation_id_alter_auditlog_action_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "flag_key",
                    models.CharField(
                        db_column="FLAG_KEY",
                        help_text="Unique key for the feature flag (e.g., new_workflow_builder)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("enabled", models.BooleanField(db_column="ENABLED", default=False)),
                (
                    "rollout_percent",
                    models.IntegerField(
                        db_column="ROLLOUT_PERCENT",
                        default=100,
                        help_text="Percentage of users to enable (0-100)",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="DESCRIPTION", default="", max_length=500
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UPDATED_AT"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, db_column="UPDATED_BY", default="", max_length=100
                    ),
                ),
            ],
            options={
                "db_table": "CORE_FEATURE_FLAGS",
                "ordering": ["flag_key"],
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("ACTION_CREATED", "Action Created"),
                    ("ACTION_UPDATED", "Action Updated"),
                    ("ACTION_PUBLISHED", "Action Published"),
                    ("ACTION_DISABLED", "Action Disabled"),
                    ("ACTION_ENABLED", "Action Enabled"),
                    ("ACTION_DELETED", "Action Deleted"),
                    ("PROFILE_CREATED", "Profile Created"),
                    ("PROFILE_UPDATED", "Profile Updated"),
                    ("PROFILE_DELETED", "Profile Deleted"),
                    ("INTEGRATION_CREATED", "Integration Created"),
                    ("INTEGRATION_UPDATED", "Integration Updated"),
                    ("INTEGRATION_DELETED", "Integration Deleted"),
                    ("EXECUTION_SUBMITTED", "Execution Submitted"),
                    ("EXECUTION_RUNNING", "Execution Running"),
                    ("EXECUTION_COMPLETED", "Execution Completed"),
                    ("EXECUTION_FAILED", "Execution Failed"),
                    ("EXECUTION_CANCELLED", "Execution Cancelled"),
                    ("EXECUTION_PENDING_APPROVAL", "Execution Pending Approval"),
                    ("EXECUTION_REJECTED", "Execution Rejected"),
                    ("EXECUTION_TARGET_FORBIDDEN", "Execution Target Forbidden"),
                    ("SCHEDULED_EXECUTION_CREATED", "Scheduled Execution Created"),
                    (
                        "SCHEDULED_EXECUTION_RECURRING_CREATED",
                        "Scheduled Execution Recurring Created",
                    ),
                    ("SCHEDULED_EXECUTION_EXECUTED", "Scheduled Execution Executed"),
                    ("SCHEDULED_EXECUTION_CANCELLED", "Scheduled Execution Cancelled"),
                    (
                        "SCHEDULED_EXECUTION_RECURRING_DISABLED",
                        "Scheduled Execution Recurring Disabled",
                    ),
                    ("USER_CREATED", "User Created"),
                    ("USER_UPDATED", "User Updated"),
                    ("USER_LOGIN", "User Login"),
                    ("USER_LOGOUT", "User Logout"),
                    ("USER_REFRESH", "User Refresh Token"),
                    ("FAVORITE_ADDED", "Favorite Added"),
                    ("FAVORITE_REMOVED", "Favorite Removed"),
                    ("EXECUTION_STEP_RETRY_ATTEMPT", "Execution Step Retry Attempt"),
                    ("EXECUTION_STEP_RETRY_SUCCESS", "Execution Step Retry Success"),
                    (
                        "EXECUTION_STEP_RETRY_EXHAUSTED",
                        "Execution Step Retry Exhausted",
                    ),
                    ("EXECUTION_STEP_RETRY_ABORTED", "Execution Step Retry Aborted"),
                    ("FEATURE_FLAG_UPDATED", "Feature Flag Updated"),
                    ("FEATURE_FLAG_CREATED", "Feature Flag Created"),
                ],
                db_column="ACTION_TYPE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("action", "Action"),
                    ("user", "User"),
                    ("permission", "Permission"),
                    ("execution", "Execution"),
                    ("integration", "Integration"),
                    ("scheduled_execution", "Scheduled Execution"),
                    ("profile", "Profile"),
                    ("feature_flag", "Feature Flag"),
                ],
                db_column="ENTITY_TYPE",
                max_length=50,
            ),
        ),
    ]
