# Generated by Django 5.2.11 on 2026-02-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('aap', 'AAP'), ('servicenow', 'ServiceNow'), ('terraform', 'Terraform'), ('azuredevops', 'Azure DevOps'), ('jira', 'Jira'), ('github_actions', 'GitHub Actions')], db_column='TYPE', max_length=50)),
                ('name', models.CharField(db_column='NAME', max_length=255, unique=True)),
                ('base_url', models.CharField(db_column='BASE_URL', max_length=2000)),
                ('credential_ref', models.CharField(blank=True, db_column='CREDENTIAL_REF', max_length=500, null=True)),
                ('icon', models.CharField(blank=True, db_column='ICON', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'db_table': 'INTEGRATIONS',
                'ordering': ['name'],
            },
        ),
    ]
