# Generated by Django 5.2.11 on 2026-02-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="auth_flow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("token", "Token"),
                    ("basic", "Basic"),
                    ("basic_then_token", "Basic Then Token"),
                    ("pat", "Personal Access Token"),
                ],
                db_column="AUTH_FLOW",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="config",
            field=models.TextField(blank=True, db_column="CONFIG", null=True),
        ),
        migrations.AddField(
            model_name="integration",
            name="token_url",
            field=models.CharField(
                blank=True, db_column="TOKEN_URL", max_length=2000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="type",
            field=models.CharField(
                choices=[
                    ("aap", "AAP"),
                    ("servicenow", "ServiceNow"),
                    ("terraform", "Terraform"),
                    ("azuredevops", "Azure DevOps"),
                    ("jira", "Jira"),
                    ("github_actions", "GitHub Actions"),
                    ("inventory", "Inventaire (API)"),
                    ("inventory_db", "Inventaire (schéma BD)"),
                ],
                db_column="TYPE",
                max_length=50,
            ),
        ),
    ]
