# Generated by Django 5.2.11 on 2026-02-10 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_integration_auth_flow_integration_config_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationTypeCatalogue",
            fields=[
                (
                    "code",
                    models.CharField(
                        db_column="CODE",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="NAME", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, db_column="DESCRIPTION", default=""),
                ),
                (
                    "version",
                    models.CharField(db_column="VERSION", default="1.0", max_length=20),
                ),
                ("is_active", models.BooleanField(db_column="IS_ACTIVE", default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CREATED_AT"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UPDATED_AT"),
                ),
            ],
            options={
                "db_table": "INTEGRATION_TYPE_CATALOGUE",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "action_code",
                    models.CharField(db_column="ACTION_CODE", max_length=100),
                ),
                (
                    "action_label",
                    models.CharField(db_column="ACTION_LABEL", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="DESCRIPTION", default=""),
                ),
                (
                    "required_params",
                    models.TextField(
                        blank=True, db_column="REQUIRED_PARAMS", default="{}"
                    ),
                ),
                (
                    "optional_params",
                    models.TextField(
                        blank=True, db_column="OPTIONAL_PARAMS", default="{}"
                    ),
                ),
                (
                    "response_format",
                    models.TextField(
                        blank=True, db_column="RESPONSE_FORMAT", default="{}"
                    ),
                ),
                ("is_active", models.BooleanField(db_column="IS_ACTIVE", default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CREATED_AT"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UPDATED_AT"),
                ),
                (
                    "integration_type",
                    models.ForeignKey(
                        db_column="INTEGRATION_TYPE_CODE",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="integrations.integrationtypecatalogue",
                    ),
                ),
            ],
            options={
                "db_table": "INTEGRATION_ACTIONS",
                "ordering": ["action_code"],
                "unique_together": {("integration_type", "action_code")},
            },
        ),
    ]
