# Generated by Django 5.2.11 on 2026-02-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_integrationtypecatalogue_integrationaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="status",
            field=models.CharField(
                choices=[
                    ("valid", "Valide"),
                    ("invalid", "Invalide"),
                    ("deprecated", "Déprécié"),
                ],
                db_column="STATUS",
                db_index=True,
                default="valid",
                max_length=20,
            ),
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IDX_INTEGRATION_STATUS ON INTEGRATIONS(STATUS)',
            reverse_sql='DROP INDEX IDX_INTEGRATION_STATUS',
        ),
    ]
