# Generated by Django 5.2.11 on 2026-02-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_add_integration_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationtypecatalogue",
            name="integration_role",
            field=models.CharField(
                choices=[
                    ("platform", "Plateforme d'exécution"),
                    ("service", "Service consommé"),
                ],
                db_column="INTEGRATION_ROLE",
                default="platform",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="type",
            field=models.CharField(
                choices=[
                    ("aap", "AAP"),
                    ("servicenow", "ServiceNow"),
                    ("terraform", "Terraform"),
                    ("terraform_cloud", "Terraform Cloud"),
                    ("azuredevops", "Azure DevOps"),
                    ("azure_devops", "Azure DevOps Pipelines"),
                    ("jira", "Jira"),
                    ("github_actions", "GitHub Actions"),
                    ("tower", "Ansible Tower"),
                    ("vault", "HashiCorp Vault"),
                    ("inventory", "Inventaire (API)"),
                    ("inventory_db", "Inventaire (schéma BD)"),
                ],
                db_column="TYPE",
                max_length=50,
            ),
        ),
    ]
