# Generated by Django 5.2.11 on 2026-02-15 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_integrationtypecatalogue_integration_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="secret_service",
            field=models.ForeignKey(
                blank=True,
                db_column="SECRET_SERVICE_ID",
                limit_choices_to={"type": "vault"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_integrations",
                to="integrations.integration",
            ),
        ),
    ]
