# Generated by Django 5.2.11 on 2026-02-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='USERNAME', max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, db_column='DISPLAY_NAME', max_length=255, null=True)),
                ('profile', models.CharField(db_column='PROFILE', max_length=50)),
                ('saml_subject', models.CharField(blank=True, db_column='SAML_SUBJECT', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'db_table': 'USERS',
                'ordering': ['username'],
            },
        ),
    ]
