"""
Django settings for idp_backend project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root (django_backend/) so AUTH_DEV_BYPASS etc. are found regardless of cwd
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Story 30.1: No hardcoded fallback - fail-fast if missing (ImproperlyConfigured)
SECRET_KEY = os.getenv('SECRET_KEY') or os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY or DJANGO_SECRET_KEY must be set in environment variables. "
        "This is a critical security setting and cannot have a default value."
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Story 30.1: DEBUG is False by default (opt-in explicit required)
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    # Third-party apps (Daphne MUST be before staticfiles per daphne.E001)
    'daphne',  # Story 22.13: ASGI server for WebSocket support (must be before staticfiles)
    # Django contrib apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Other third-party apps
    'rest_framework',
    'drf_spectacular',  # Story 22.20: OpenAPI/Swagger documentation
    'corsheaders',
    'channels',  # Story 22.13: Django Channels for WebSocket
    # Local apps
    'catalog',
    'profiles',
    'idp_auth',
    'integrations',
    'core',
    'executions',
    'inventory',
    'reference',
    'help',  # Story 31.7 - Aide contextuelle
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.CorrelationIdMiddleware',  # Story M.7 - correlation ID first
    'core.db_resilience.DatabaseResilienceMiddleware',  # Story 32.1 - DB failover detection + retry
    'core.middleware.RequestResponseLoggingMiddleware',  # Story M.8 - request/response logging
    'core.middleware.RateLimitHeadersMiddleware',  # Story 17.11 - rate limit headers + logging
    'core.middleware.SecurityHeadersMiddleware',  # Story M.7 - security headers
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware should be early
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'idp_auth.middleware.AuditAuthMiddleware',  # Story M.7 - auth audit logging
]

ROOT_URLCONF = 'idp_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'idp_backend.wsgi.application'
ASGI_APPLICATION = 'idp_backend.asgi.application'  # Story 22.13: WebSocket via Channels


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Oracle Database configuration
# Uses standard Oracle environment variables
# ORACLE_CLIENT_LIB: path to Oracle Instant Client dir (enables thick mode, required for
#   TIMESTAMP WITH TIME ZONE / DPY-3022 "named time zones not supported in thin mode")
ORACLE_DSN = os.getenv('ORACLE_DSN', 'localhost:1521/FREEPDB1')
ORACLE_USER = os.getenv('ORACLE_USER', 'idp_app')
# Story 17.5: No hardcoded default - fail-fast if missing in production
ORACLE_PASSWORD = os.getenv('ORACLE_PASSWORD', '')

# Story 32.1: DB resilience settings for Data Guard failover/switchover
# CONN_MAX_AGE: Max lifetime of a DB connection (seconds). After failover,
# new requests get fresh connections once old ones expire.
DB_CONN_MAX_AGE = int(os.getenv('DB_CONN_MAX_AGE', '600'))
# CONN_HEALTH_CHECKS: Django 4.1+ — validates connection before reuse.
# If dead (post-failover), Django silently recreates it. Key resilience mechanism.
DB_CONN_HEALTH_CHECKS = os.getenv('DB_CONN_HEALTH_CHECKS', 'True').lower() in ('true', '1', 'yes')
# Story 32.2: Retry settings for transactional retry after DB reconnection
# Max retry attempts before returning 503 (first attempt is immediate)
DB_RETRY_MAX_ATTEMPTS = int(os.getenv('DB_RETRY_MAX_ATTEMPTS', '3'))
# Base delay for exponential backoff between retries (seconds), capped at 5s
DB_RETRY_BACKOFF_BASE = float(os.getenv('DB_RETRY_BACKOFF_BASE', '0.5'))
# Story 32.4: Max total duration for all retry attempts (seconds).
# Aligns with Data Guard FSFO < 1 min — default 120s is a generous upper bound.
DB_RETRY_TIME_WINDOW_SECONDS = int(os.getenv('DB_RETRY_TIME_WINDOW_SECONDS', '120'))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': ORACLE_DSN,
        'USER': ORACLE_USER,
        'PASSWORD': ORACLE_PASSWORD,
        'CONN_MAX_AGE': DB_CONN_MAX_AGE,
        'CONN_HEALTH_CHECKS': DB_CONN_HEALTH_CHECKS,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Ensure static/icons/ directory exists so STATICFILES_DIRS always includes it.
# Without this, if Django starts before any icon is uploaded, the dir doesn't exist,
# STATICFILES_DIRS becomes [] and StaticFilesHandler can't serve uploaded icons
# even after they're written to disk (finders are loaded once at startup).
(BASE_DIR / 'static' / 'icons').mkdir(parents=True, exist_ok=True)
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'idp_auth.authentication.JWTAuthentication',  # Story M.7
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Story M.7 - default to authenticated
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'core.throttling.GeneralAPIThrottle',  # Story 17.11 - default rate limit for all API endpoints
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth': os.getenv('THROTTLE_AUTH_RATE', '10/minute'),
        'token_refresh': os.getenv('THROTTLE_TOKEN_REFRESH_RATE', '20/minute'),
        'execution': os.getenv('THROTTLE_EXECUTION_RATE', '30/minute'),
        'general_api': os.getenv('THROTTLE_API_RATE', '100/minute'),
        'public': os.getenv('THROTTLE_PUBLIC_RATE', '50/minute'),
        'api_key_token': os.getenv('THROTTLE_API_KEY_TOKEN_RATE', '10/minute'),
    },
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 25,
    # Custom exception handler for standardized error format
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    # Format response in snake_case (not camelCase)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    # Story 22.20: drf-spectacular OpenAPI schema generation
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ============================================================================
# drf-spectacular Configuration (Story 22.20 - OpenAPI/Swagger Documentation)
# ============================================================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'DBOps Portal API',
    'DESCRIPTION': "API REST pour le portail DBOps — Gestion et exécution d'actions DBA",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/v1',
    'SECURITY': [{'bearerAuth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    'TAGS': [
        {'name': 'catalog', 'description': "Gestion du catalogue d'actions"},
        {'name': 'executions', 'description': "Exécution et suivi des actions"},
        {'name': 'profiles', 'description': "Gestion des profils et permissions RBAC"},
        {'name': 'inventory', 'description': "Inventaire des targets et environnements — **Usage interne uniquement** (non exposé dans la doc publique)"},
        {'name': 'integrations', 'description': "Intégrations plateformes distantes"},
        {'name': 'audit', 'description': "Audit trail et conformité SOC1"},
        {'name': 'auth', 'description': "Authentification SAML et JWT"},
        {'name': 'reference', 'description': "Données de référence (engines, platforms, catégories)"},
        {'name': 'dashboard', 'description': "Dashboard et analytics"},
        {'name': 'scheduling', 'description': "Planification et exécutions programmées"},
    ],
}

# ============================================================================
# Cache Configuration (Story 17.11 - Rate Limiting, Story 20.3 - Cancellation Cache)
# ============================================================================
# Story 20.3: Redis cache required for cancellation cache (AC5) to work in production
# Fallback to LocMemCache if Redis is not available (development/Docker without Redis)
# Set CACHE_BACKEND=locmem to force in-memory cache, or CACHE_BACKEND=redis to use Redis
CACHE_BACKEND = os.getenv('CACHE_BACKEND', 'redis').lower()

if CACHE_BACKEND == 'locmem':
    # Use in-memory cache (works without Redis, but not shared across processes/containers)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'idp-portal-cache',
        }
    }
else:
    # Use Redis cache (default for production)
    # Note: If Redis is unavailable, Django will raise ConnectionError on cache access
    # For Docker/CI environments without Redis, set CACHE_BACKEND=locmem
    redis_url = os.getenv('REDIS_URL', 'redis://localhost:6379/1')
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': redis_url,
        }
    }

# Rate limiting enable/disable flag (Story 17.11)
RATELIMIT_ENABLED = os.getenv('RATELIMIT_ENABLED', 'true').lower() == 'true'

# ============================================================================
# Feature Flags Configuration (Story 17.12, 22.16)
# ============================================================================
# Source: 'env' (from FEATURE_FLAGS JSON env var) or 'database' (from CORE_FEATURE_FLAGS table)
FEATURE_FLAGS_SOURCE = os.getenv('FEATURE_FLAGS_SOURCE', 'env')
# Global enable/disable for the feature flags system
FEATURE_FLAGS_ENABLED = os.getenv('FEATURE_FLAGS_ENABLED', 'true').lower() == 'true'
# Cache TTL in seconds (default 5 minutes)
FEATURE_FLAGS_CACHE_TTL = int(os.getenv('FEATURE_FLAGS_CACHE_TTL', '300'))
# JSON-encoded feature flags from environment (used when FEATURE_FLAGS_SOURCE=env)
FEATURE_FLAGS = os.getenv('FEATURE_FLAGS', '{}')

# Story 22.16: Anti-thundering herd lock timeout (seconds)
# Timeout for distributed lock when cache expires. Prevents concurrent DB loads.
# CRITICAL: Requires distributed cache backend (Redis/Memcached) in production.
# LocMemCache provides per-process locking only.
FEATURE_FLAGS_LOCK_TIMEOUT = int(os.getenv('FEATURE_FLAGS_LOCK_TIMEOUT', '3'))

# CORS configuration (Story M.8 - Task 7)
# NOTE: Default value is for development only. MUST be configured via CORS_ORIGIN env var in production.
CORS_ALLOWED_ORIGINS = [
    os.getenv('CORS_ORIGIN', 'http://localhost:5173'),
]

# Allow credentials (cookies) for httpOnly refresh token
CORS_ALLOW_CREDENTIALS = True

# Expose correlation ID header to frontend for debugging
CORS_EXPOSE_HEADERS = [
    'X-Correlation-ID',  # SEC-9: Unified with frontend (was X-Idp-Request-Id)
    'Retry-After',  # Story 17.11 - rate limit headers
    'X-RateLimit-Limit',
    'X-RateLimit-Remaining',
    'X-RateLimit-Reset',
]

# Allowed headers from frontend
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-correlation-id',  # SEC-9: Unified with frontend (was x-idp-request-id)
    'x-api-key',  # Story 44.2 - API key token exchange endpoint
]

# ============================================================================
# SAML Configuration (Story M.7)
# ============================================================================

# Service Provider (SP) settings
SAML_SP_ENTITY_ID = os.getenv('SAML_SP_ENTITY_ID', 'https://idp-portal.example.com/metadata')
SAML_SP_ACS_URL = os.getenv('SAML_SP_ACS_URL', 'http://localhost:8000/api/v1/auth/saml/callback')
SAML_SP_CERT_PATH = os.getenv('SAML_SP_CERT_PATH', '')
SAML_SP_KEY_PATH = os.getenv('SAML_SP_KEY_PATH', '')

# Identity Provider (IdP) settings
SAML_IDP_ENTITY_ID = os.getenv('SAML_IDP_ENTITY_ID', 'https://idp.example.com/entity')
SAML_IDP_SSO_URL = os.getenv('SAML_IDP_SSO_URL', 'https://idp.example.com/sso')
SAML_IDP_SLO_URL = os.getenv('SAML_IDP_SLO_URL', 'https://idp.example.com/slo')
SAML_IDP_CERT_PATH = os.getenv('SAML_IDP_CERT_PATH', '')

# ============================================================================
# JWT Configuration (Story M.7)
# ============================================================================

# Story 30.1: No hardcoded default - fail-fast if missing (ImproperlyConfigured)
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')
if not JWT_SECRET_KEY:
    raise ImproperlyConfigured(
        "JWT_SECRET_KEY must be set in environment variables and cannot be empty. "
        "This is required for secure JWT token generation and validation."
    )
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv('JWT_ACCESS_TOKEN_EXPIRE_MINUTES', '30'))
JWT_REFRESH_TOKEN_EXPIRE_HOURS = int(os.getenv('JWT_REFRESH_TOKEN_EXPIRE_HOURS', '8'))

# ============================================================================
# Auth Configuration
# ============================================================================

# Dev bypass for local development without IdP (Story M.7)
AUTH_DEV_BYPASS = os.getenv('AUTH_DEV_BYPASS', 'False').lower() == 'true'

# Story 22.2 CRIT-2: Superuser fallback control for RBAC bypass
# Controls whether Django superusers can bypass DBOPS profile requirement.
# When False (default): superusers WITHOUT a DBOPS profile are DENIED access (fail-secure)
# When True (dev only): superusers WITHOUT a DBOPS profile are granted access with WARNING log
# SECURITY: Must be False in production to enforce principle of least privilege
ALLOW_SUPERUSER_FALLBACK = os.getenv('ALLOW_SUPERUSER_FALLBACK', 'false').lower() == 'true'

# Application environment
APP_ENV = os.getenv('APP_ENV', 'development')

# ============================================================================
# Execution Simulation Configuration (Story 19.0)
# ============================================================================
# Enables simulated execution progression in dev mode (no real platform calls)
SIMULATE_EXECUTION_DEV = os.getenv('SIMULATE_EXECUTION_DEV', str(DEBUG)).lower() == 'true'
# Probability of a simulated execution failing (0.0 = never, 1.0 = always)
SIMULATE_EXECUTION_FAILURE_RATE = float(os.getenv('SIMULATE_EXECUTION_FAILURE_RATE', '0.1'))
# Duration in seconds for each simulated step
SIMULATE_EXECUTION_STEP_DURATION = int(os.getenv('SIMULATE_EXECUTION_STEP_DURATION', '2'))

# ============================================================================
# Logging Configuration (Story M.8)
# ============================================================================

# Log level from environment (default INFO for production)
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').upper()

# Django LOGGING configuration that works with structlog
# structlog is configured in core.apps.CoreConfig.ready()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# ============================================================================
# Production Security Settings (Story 15.3 - SOC1/NFR6)
# ============================================================================
# These settings enforce TLS/HTTPS in production (when DEBUG=False).

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ============================================================================
# Celery Configuration (Story 20.3 - Asynchronous retry)
# ============================================================================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_ALWAYS_EAGER = os.getenv('CELERY_TASK_ALWAYS_EAGER', 'False').lower() == 'true'
CELERY_TASK_EAGER_PROPAGATES = True

# ============================================================================
# Django Channels / WebSocket Configuration (Story 22.13)
# ============================================================================
# Uses InMemoryChannelLayer for development; switch to Redis for production.
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# ============================================================================
# Workflow Retry Configuration (Story 20.3)
# ============================================================================
# Enable Redis cache for cancellation status check (AC5)
# Default: False (use refresh_from_db). Enable for production with >100 active workflows.
WORKFLOW_RETRY_USE_CANCELLATION_CACHE = os.getenv(
    'WORKFLOW_RETRY_USE_CANCELLATION_CACHE', 'False'
).lower() == 'true'

# ============================================================================
# External Services Configuration (Story M.8 - Health Check)
# ============================================================================

# Vault configuration for health check
VAULT_ADDR = os.getenv('VAULT_ADDR', 'http://localhost:8200')

# ServiceNow configuration for health check and ITSM integration
SERVICENOW_INSTANCE_URL = os.getenv('SERVICENOW_INSTANCE_URL', 'https://instance.service-now.com')
# TLS verification for ServiceNow API calls (default True); set SERVICENOW_VERIFY_TLS=false to disable
SERVICENOW_VERIFY_TLS = os.getenv('SERVICENOW_VERIFY_TLS', 'true').lower() == 'true'

# Story 31.8: Notification service configuration
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'idp-portal@example.com')
PAGE_INDIVIDUAL_API_URL = os.getenv('PAGE_INDIVIDUAL_API_URL', '')
PAGE_DBA_API_URL = os.getenv('PAGE_DBA_API_URL', '')
