"""
Django settings for idp_backend project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# NOTE: Default value is for development only. MUST be set via SECRET_KEY env var in production.
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-bvc0qsxvq0dly--u$d1pge47!6f^r+wf%9e4c^2sn!=z(-wkqf')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    # Local apps
    'catalog',
    'profiles',
    'idp_auth',
    'integrations',
    'core',
    'executions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.CorrelationIdMiddleware',  # Story M.7 - correlation ID first
    'core.middleware.RequestResponseLoggingMiddleware',  # Story M.8 - request/response logging
    'core.middleware.SecurityHeadersMiddleware',  # Story M.7 - security headers
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware should be early
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'idp_auth.middleware.AuditAuthMiddleware',  # Story M.7 - auth audit logging
]

ROOT_URLCONF = 'idp_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'idp_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Oracle Database configuration
# Uses same environment variables as FastAPI backend
ORACLE_DSN = os.getenv('ORACLE_DSN', 'localhost:1521/FREEPDB1')
ORACLE_USER = os.getenv('ORACLE_USER', 'idp_app')
ORACLE_PASSWORD = os.getenv('ORACLE_PASSWORD', 'changeme')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': ORACLE_DSN,
        'USER': ORACLE_USER,
        'PASSWORD': ORACLE_PASSWORD,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'idp_auth.authentication.JWTAuthentication',  # Story M.7
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Story M.7 - default to authenticated
    ],
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 25,
    # Custom exception handler to match FastAPI error format
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    # Format response in snake_case (not camelCase)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# CORS configuration (Story M.8 - Task 7)
# NOTE: Default value is for development only. MUST be configured via CORS_ORIGIN env var in production.
CORS_ALLOWED_ORIGINS = [
    os.getenv('CORS_ORIGIN', 'http://localhost:5173'),
]

# Allow credentials (cookies) for httpOnly refresh token
CORS_ALLOW_CREDENTIALS = True

# Expose correlation ID header to frontend for debugging
CORS_EXPOSE_HEADERS = [
    'X-Idp-Request-Id',
]

# Allowed headers from frontend
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-idp-request-id',  # Allow frontend to pass correlation ID
]

# ============================================================================
# SAML Configuration (Story M.7 - mirrors FastAPI settings)
# ============================================================================

# Service Provider (SP) settings
SAML_SP_ENTITY_ID = os.getenv('SAML_SP_ENTITY_ID', 'https://idp-portal.example.com/metadata')
SAML_SP_ACS_URL = os.getenv('SAML_SP_ACS_URL', 'http://localhost:8000/api/v1/auth/saml/callback')
SAML_SP_CERT_PATH = os.getenv('SAML_SP_CERT_PATH', '')
SAML_SP_KEY_PATH = os.getenv('SAML_SP_KEY_PATH', '')

# Identity Provider (IdP) settings
SAML_IDP_ENTITY_ID = os.getenv('SAML_IDP_ENTITY_ID', 'https://idp.example.com/entity')
SAML_IDP_SSO_URL = os.getenv('SAML_IDP_SSO_URL', 'https://idp.example.com/sso')
SAML_IDP_SLO_URL = os.getenv('SAML_IDP_SLO_URL', 'https://idp.example.com/slo')
SAML_IDP_CERT_PATH = os.getenv('SAML_IDP_CERT_PATH', '')

# ============================================================================
# JWT Configuration (Story M.7 - mirrors FastAPI settings)
# ============================================================================

JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', 'change-me-in-production')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv('JWT_ACCESS_TOKEN_EXPIRE_MINUTES', '30'))
JWT_REFRESH_TOKEN_EXPIRE_HOURS = int(os.getenv('JWT_REFRESH_TOKEN_EXPIRE_HOURS', '8'))

# ============================================================================
# Auth Configuration
# ============================================================================

# Dev bypass for local development without IdP (Story M.7)
AUTH_DEV_BYPASS = os.getenv('AUTH_DEV_BYPASS', 'False').lower() == 'true'

# Application environment
APP_ENV = os.getenv('APP_ENV', 'development')

# ============================================================================
# Logging Configuration (Story M.8)
# ============================================================================

# Log level from environment (default INFO for production)
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').upper()

# Django LOGGING configuration that works with structlog
# structlog is configured in core.apps.CoreConfig.ready()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# ============================================================================
# External Services Configuration (Story M.8 - Health Check)
# ============================================================================

# Vault configuration for health check
VAULT_ADDR = os.getenv('VAULT_ADDR', 'http://localhost:8200')

# ServiceNow configuration for health check
SERVICENOW_INSTANCE_URL = os.getenv('SERVICENOW_INSTANCE_URL', 'https://instance.service-now.com')
